### ISSUE TITLE
[BUG] ValueError: Cannot load file containing pickled data when allow_pickle=False

### ISSUE THREAD

**Issue by centrdev** [IAHispano/Applio#195]
**Describe the bug**
Get error when starting training.

**Desktop (please complete the following information):**
 - OS: Windows 11

**ERROR MESSAGE**
`Starting training...
D:\Applio\env\lib\site-packages\torch\autograd\__init__.py:251: UserWarning: Grad strides do not match bucket view strides. This may indicate grad was not created according to the gradient layout contract, or that the param's strides changed since DDP was constructed.  This is not an error, but may impair performance.
grad.sizes() = [1, 21, 96], strides() = [57120, 96, 1]
bucket_view.sizes() = [1, 21, 96], strides() = [2016, 96, 1] (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\distributed\c10d\reducer.cpp:334.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
Process Process-1:
Traceback (most recent call last):
  File "D:\Applio\env\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "D:\Applio\env\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Applio\rvc\train\train.py", line 259, in run
    train_and_evaluate(
  File "D:\Applio\rvc\train\train.py", line 374, in train_and_evaluate
    for batch_idx, info in data_iterator:
  File "D:\Applio\env\lib\site-packages\torch\utils\data\dataloader.py", line 630, in __next__
    data = self._next_data()
  File "D:\Applio\env\lib\site-packages\torch\utils\data\dataloader.py", line 1325, in _next_data
    return self._process_data(data)
  File "D:\Applio\env\lib\site-packages\torch\utils\data\dataloader.py", line 1371, in _process_data
    data.reraise()
  File "D:\Applio\env\lib\site-packages\torch\_utils.py", line 694, in reraise
    raise exception
ValueError: Caught ValueError in DataLoader worker process 2.
Original Traceback (most recent call last):
  File "D:\Applio\env\lib\site-packages\torch\utils\data\_utils\worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "D:\Applio\env\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\Applio\env\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\Applio\rvc\train\data_utils.py", line 288, in __getitem__
    return self.get_audio_text_pair(self.audiopaths_and_text[index])
  File "D:\Applio\rvc\train\data_utils.py", line 228, in get_audio_text_pair
    phone = self.get_labels(phone)
  File "D:\Applio\rvc\train\data_utils.py", line 243, in get_labels
    phone = np.load(phone)
  File "D:\Applio\env\lib\site-packages\numpy\lib\npyio.py", line 438, in load
    raise ValueError("Cannot load file containing pickled data "
ValueError: Cannot load file containing pickled data when allow_pickle=False`

**Comment by cheezebone** [comment]
I have the same problem.

**Comment by aitronssesin** [comment]
We are currently trying to find a solution we know is a current error rn.

**Comment by blaise-tk** [comment]
Fixed.
