### ISSUE TITLE
[BUG] after installing everything running the run-install.sh // it has this error

### ISSUE THREAD

**Issue by fellowballsack** [IAHispano/Applio#200]
so after doing the command to install everything it tells me i can use the run-applio.sh but when i run it i get this error. 

Traceback (most recent call last):
  File "/Users/supermom/Downloads/Applio-main/app.py", line 12, in <module>
    from tabs.inference.inference import inference_tab
  File "/Users/supermom/Downloads/Applio-main/tabs/inference/inference.py", line 3, in <module>
    import regex as re
ModuleNotFoundError: No module named 'regex'

**Comment by sonphantrung** [comment]
Change the line in tabs/inference/inference.py from `import regex as re` to `import re`

**Comment by fellowballsack** [comment]
ok so it worked but now theres this 


Traceback (most recent call last):
  File "/Users/supermom/Downloads/Applio-main/app.py", line 12, in <module>
    from tabs.inference.inference import inference_tab
  File "/Users/supermom/Downloads/Applio-main/tabs/inference/inference.py", line 8, in <module>
    from core import (
  File "/Users/supermom/Downloads/Applio-main/core.py", line 9, in <module>
    from rvc.configs.config import Config
  File "/Users/supermom/Downloads/Applio-main/rvc/configs/config.py", line 7, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'

**Comment by sonphantrung** [comment]
What's your GPU? Maybe try installing Pytorch [manually](https://pytorch.org/get-started/locally/)

**Comment by blaise-tk** [comment]
Hey! Any update here?

**Comment by sonphantrung** [comment]
> Hey! Any update here?

SciPy is >=3.9 [btw](https://pypi.org/project/SciPy/)

**Comment by blaise-tk** [comment]
> > Hey! Any update here?
> 
> SciPy is >=3.9 [btw](https://pypi.org/project/SciPy/)

wdym?

**Comment by sonphantrung** [comment]
> > > Hey! Any update here?
> > 
> > 
> > SciPy is >=3.9 [btw](https://pypi.org/project/SciPy/)
> 
> wdym?

Maybe he's on systems where their Python version is unsupported by SciPy (like 3.8), and when running the script, it errored out, thus leading to other dependencies (like Torch) not properly installed.

**Comment by blaise-tk** [comment]
Should be fixed.
