### ISSUE TITLE
[BUG] Could not find Discord installed and running on this machine

### ISSUE THREAD

**Issue by Qualzz** [IAHispano/Applio#215]
If you start applio while not having launched discord, it raise this error `Could not find Discord installed and running on this machine` and prevent the server to start.

Full message:
```
Traceback (most recent call last):
  File "xxxx\app.py", line 20, in <module>
    rich_presence()
  File "xxxx\assets\discord_presence.py", line 9, in rich_presence
    RPC.connect()
  File "xxxx\env\lib\site-packages\pypresence\presence.py", line 43, in connect
    self.loop.run_until_complete(self.handshake())
  File "xxxx\env\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "xxxx\env\lib\site-packages\pypresence\baseclient.py", line 108, in handshake
    raise DiscordNotFound
pypresence.exceptions.DiscordNotFound: Could not find Discord installed and running on this machine.
```
This is related to applio wanting to interact with our discord instance to display that we are using applio to friends etc, however this shouldn't be mandatory or prevent the use of applio itself. Maybe add an option to opt-in/out from the app ?

**Comment by blaise-tk** [comment]
This is fixed in the last version, please download it

**Comment by Qualzz** [comment]
Well done !
