### ISSUE TITLE
[BUG] Inferencias  ( en mac) 

### ISSUE THREAD

**Issue by Anthonyxd22** [IAHispano/Applio#220]
No supported Nvidia GPU found
<All keys matched successfully>
2024-01-21 13:51:54 | INFO | fairseq.tasks.hubert_pretraining | current directory is /Users/anthony/Downloads/Applio-3.0.3
2024-01-21 13:51:54 | INFO | fairseq.tasks.hubert_pretraining | HubertPretrainingTask Config {'_name': 'hubert_pretraining', 'data': 'metadata', 'fine_tuning': False, 'labels': ['km'], 'label_dir': 'label', 'label_rate': 50.0, 'sample_rate': 16000, 'normalize': False, 'enable_padding': False, 'max_keep_size': None, 'max_sample_size': 250000, 'min_sample_size': 32000, 'single_target': False, 'random_crop': True, 'pad_audio': False}
2024-01-21 13:51:54 | INFO | fairseq.models.hubert.hubert | HubertModel Config: {'_name': 'hubert', 'label_rate': 50.0, 'extractor_mode': default, 'encoder_layers': 12, 'encoder_embed_dim': 768, 'encoder_ffn_embed_dim': 3072, 'encoder_attention_heads': 12, 'activation_fn': gelu, 'layer_type': transformer, 'dropout': 0.1, 'attention_dropout': 0.1, 'activation_dropout': 0.0, 'encoder_layerdrop': 0.05, 'dropout_input': 0.1, 'dropout_features': 0.1, 'final_dim': 256, 'untie_final_proj': True, 'layer_norm_first': False, 'conv_feature_layers': '[(512,10,5)] + [(512,3,2)] * 4 + [(512,2,2)] * 2', 'conv_bias': False, 'logit_temp': 0.1, 'target_glu': False, 'feature_grad_mult': 0.1, 'mask_length': 10, 'mask_prob': 0.8, 'mask_selection': static, 'mask_other': 0.0, 'no_mask_overlap': False, 'mask_min_space': 1, 'mask_channel_length': 10, 'mask_channel_prob': 0.0, 'mask_channel_selection': static, 'mask_channel_other': 0.0, 'no_mask_channel_overlap': False, 'mask_channel_min_space': 1, 'conv_pos': 128, 'conv_pos_groups': 16, 'latent_temp': [2.0, 0.5, 0.999995], 'skip_masked': False, 'skip_nomask': False, 'checkpoint_activations': False, 'required_seq_len_multiple': 2, 'depthwise_conv_kernel_size': 31, 'attn_type': '', 'pos_enc_type': 'abs', 'fp16': False}
/Users/anthony/Downloads/Applio-3.0.3/.venv/lib/python3.9/site-packages/torch/nn/utils/weight_norm.py:30: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
^[The operator 'aten::_weight_norm_interface' is not currently implemented for the MPS device. If you want this op to be added in priority during the prototype phase of this feature, please comment on https://github.com/pytorch/pytorch/issues/77764. As a temporary fix, you can set the environment variable `PYTORCH_ENABLE_MPS_FALLBACK=1` to use the CPU as a fallback for this op. WARNING: this will be slower than running natively on MPS.
Voice conversion failed: cannot unpack non-iterable NoneType object
Traceback (most recent call last):
  File "/Users/anthony/Downloads/Applio-3.0.3/.venv/lib/python3.9/site-packages/gradio/queueing.py", line 495, in call_prediction
    output = await route_utils.call_process_api(
  File "/Users/anthony/Downloads/Applio-3.0.3/.venv/lib/python3.9/site-packages/gradio/route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "/Users/anthony/Downloads/Applio-3.0.3/.venv/lib/python3.9/site-packages/gradio/blocks.py", line 1570, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/Users/anthony/Downloads/Applio-3.0.3/.venv/lib/python3.9/site-packages/gradio/blocks.py", line 1456, in postprocess_data
    outputs_cached = processing_utils.move_files_to_cache(
  File "/Users/anthony/Downloads/Applio-3.0.3/.venv/lib/python3.9/site-packages/gradio/processing_utils.py", line 265, in move_files_to_cache
    return client_utils.traverse(data, _move_to_cache, client_utils.is_file_obj)
  File "/Users/anthony/Downloads/Applio-3.0.3/.venv/lib/python3.9/site-packages/gradio_client/utils.py", line 919, in traverse
    return func(json_obj)
  File "/Users/anthony/Downloads/Applio-3.0.3/.venv/lib/python3.9/site-packages/gradio/processing_utils.py", line 257, in _move_to_cache
    temp_file_path = move_resource_to_block_cache(payload.path, block)
  File "/Users/anthony/Downloads/Applio-3.0.3/.venv/lib/python3.9/site-packages/gradio/processing_utils.py", line 234, in move_resource_to_block_cache
    return block.move_resource_to_block_cache(url_or_file_path)
  File "/Users/anthony/Downloads/Applio-3.0.3/.venv/lib/python3.9/site-packages/gradio/blocks.py", line 258, in move_resource_to_block_cache
    temp_file_path = processing_utils.save_file_to_cache(
  File "/Users/anthony/Downloads/Applio-3.0.3/.venv/lib/python3.9/site-packages/gradio/processing_utils.py", line 170, in save_file_to_cache
    temp_dir = hash_file(file_path)
  File "/Users/anthony/Downloads/Applio-3.0.3/.venv/lib/python3.9/site-packages/gradio/processing_utils.py", line 102, in hash_file
    with open(file_path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/anthony/Downloads/Applio-3.0.3/assets/audios/leaked_output.wav'

**Comment by Anthonyxd22** [comment]
Cuando le toco a convert me da error y aparecen eso la terminal

**Comment by Anthonyxd22** [comment]
<img width="1258" alt="Captura de pantalla 2024-01-21 a la(s) 1 57 59 p m" src="https://github.com/IAHispano/Applio/assets/144498068/23ffe853-0d79-4bb1-984f-cffa6a60e191">

**Comment by blaise-tk** [comment]
![image](https://github.com/IAHispano/Applio/assets/133521603/1f1baf50-1847-43be-a42c-f8d866f162ac)
