### ISSUE TITLE
[BUG] TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by Suk0803** [IAHispano/Applio#225]
When executing 'run-applio.sh', the following type error occurs.

```
Traceback (most recent call last):
  File "/Users/user_name/Desktop/Applio-3.0.3/app.py", line 10, in <module>
    i18n = I18nAuto()
           ^^^^^^^^^^
  File "/Users/user_name/Desktop/Applio-3.0.3/assets/i18n/i18n.py", line 15, in __init__
    lang_prefix = language[:2]
                  ~~~~~~~~^^^^
TypeError: 'NoneType' object is not subscriptable
```

**Desktop: M1 Max Mac Studio **
 - OS: MacOS Sonoma version 14.0
 - Browser: chrome

**Comment by blaise-tk** [comment]
Try with the last version, should be fixed https://github.com/IAHispano/Applio/pull/216

**Comment by Suk0803** [comment]
Thank you, problem-solved!
