### ISSUE TITLE
[BUG] ValueError: mutable default <class 'fairseq.dataclass.configs.CommonConfig'> for field common is not allowed: use default_factory / FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by Suk0803** [IAHispano/Applio#229]
When I run convert, I get two errors like this.
1. `ValueError: mutable default <class 'fairseq.dataclass.configs.CommonConfig'> for field common is not allowed: use default_factory`
2. `FileNotFoundError: [Errno 2] No such file or directory`

### full log
```

/Users/user/Desktop/ap/Applio-3.0.4/.venv/lib/python3.11/site-packages/pydub/utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
Traceback (most recent call last):
  File "/Users/user/Desktop/ap/Applio-3.0.4/rvc/infer/infer.py", line 9, in <module>
    from fairseq import checkpoint_utils
  File "/Users/user/Desktop/ap/Applio-3.0.4/.venv/lib/python3.11/site-packages/fairseq/__init__.py", line 20, in <module>
    from fairseq.distributed import utils as distributed_utils
  File "/Users/user/Desktop/ap/Applio-3.0.4/.venv/lib/python3.11/site-packages/fairseq/distributed/__init__.py", line 7, in <module>
    from .fully_sharded_data_parallel import (
  File "/Users/user/Desktop/ap/Applio-3.0.4/.venv/lib/python3.11/site-packages/fairseq/distributed/fully_sharded_data_parallel.py", line 10, in <module>
    from fairseq.dataclass.configs import DistributedTrainingConfig
  File "/Users/user/Desktop/ap/Applio-3.0.4/.venv/lib/python3.11/site-packages/fairseq/dataclass/__init__.py", line 6, in <module>
    from .configs import FairseqDataclass
  File "/Users/user/Desktop/ap/Applio-3.0.4/.venv/lib/python3.11/site-packages/fairseq/dataclass/configs.py", line 1104, in <module>
    @dataclass
     ^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/dataclasses.py", line 1230, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/dataclasses.py", line 1220, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/dataclasses.py", line 958, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'fairseq.dataclass.configs.CommonConfig'> for field common is not allowed: use default_factory
Traceback (most recent call last):
  File "/Users/user/Desktop/ap/Applio-3.0.4/.venv/lib/python3.11/site-packages/gradio/queueing.py", line 495, in call_prediction
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/Desktop/ap/Applio-3.0.4/.venv/lib/python3.11/site-packages/gradio/route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/Desktop/ap/Applio-3.0.4/.venv/lib/python3.11/site-packages/gradio/blocks.py", line 1570, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/Desktop/ap/Applio-3.0.4/.venv/lib/python3.11/site-packages/gradio/blocks.py", line 1456, in postprocess_data
    outputs_cached = processing_utils.move_files_to_cache(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/Desktop/ap/Applio-3.0.4/.venv/lib/python3.11/site-packages/gradio/processing_utils.py", line 265, in move_files_to_cache
    return client_utils.traverse(data, _move_to_cache, client_utils.is_file_obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/Desktop/ap/Applio-3.0.4/.venv/lib/python3.11/site-packages/gradio_client/utils.py", line 919, in traverse
    return func(json_obj)
           ^^^^^^^^^^^^^^
  File "/Users/user/Desktop/ap/Applio-3.0.4/.venv/lib/python3.11/site-packages/gradio/processing_utils.py", line 257, in _move_to_cache
    temp_file_path = move_resource_to_block_cache(payload.path, block)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/Desktop/ap/Applio-3.0.4/.venv/lib/python3.11/site-packages/gradio/processing_utils.py", line 234, in move_resource_to_block_cache
    return block.move_resource_to_block_cache(url_or_file_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/Desktop/ap/Applio-3.0.4/.venv/lib/python3.11/site-packages/gradio/blocks.py", line 258, in move_resource_to_block_cache
    temp_file_path = processing_utils.save_file_to_cache(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/Desktop/ap/Applio-3.0.4/.venv/lib/python3.11/site-packages/gradio/processing_utils.py", line 170, in save_file_to_cache
    temp_dir = hash_file(file_path)
               ^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/Desktop/ap/Applio-3.0.4/.venv/lib/python3.11/site-packages/gradio/processing_utils.py", line 102, in hash_file
    with open(file_path, "rb") as f:
         ^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/Users/user/Desktop/ap/Applio-3.0.4/assets/audios/test
.wav'
```

**Assets**
<img width="1517" alt="Screenshot 2024-01-23 at 11 57 50 AM" src="https://github.com/IAHispano/Applio/assets/50763770/121d8f03-1175-49b1-bab6-97a327247ac2">

Desktop: M1 Max Mac Studio 
OS: MacOS Sonoma version 14.0
Browser: chrome
Applio version : 3.0.4

**Comment by aitronssesin** [comment]
Apple devices are not currently available

![image](https://github.com/IAHispano/Applio/assets/74368135/ca7d7006-22c9-46a5-95bf-9aa652fd6e8d)
