### ISSUE TITLE
[BUG] v3.0.4

### ISSUE THREAD

**Issue by planetrenox** [IAHispano/Applio#260]
**Describe the bug**
Fresh install of v3.0.4

**To Reproduce**
1. TTS

**Desktop:**
 - OS: Windows 10
 - Browser Firefox

**Additional context**
TTS with en-US-AvaNeural completed. Output TTS file: 'D:\OneDrive\Music\TTS\Applio-3.0.4\assets\audios\tts_output.wav'
Traceback (most recent call last):
  File "D:\OneDrive\Music\TTS\Applio-3.0.4\rvc\infer\infer.py", line 241, in <module>
    get_vc(model_path, 0)
  File "D:\OneDrive\Music\TTS\Applio-3.0.4\rvc\infer\infer.py", line 187, in get_vc
    cpt = torch.load(person, map_location="cpu")
  File "D:\OneDrive\Music\TTS\Applio-3.0.4\env\lib\site-packages\torch\serialization.py", line 986, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "D:\OneDrive\Music\TTS\Applio-3.0.4\env\lib\site-packages\torch\serialization.py", line 435, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "D:\OneDrive\Music\TTS\Applio-3.0.4\env\lib\site-packages\torch\serialization.py", line 416, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: ''
Traceback (most recent call last):
  File "D:\OneDrive\Music\TTS\Applio-3.0.4\env\lib\site-packages\gradio\queueing.py", line 495, in call_prediction
    output = await route_utils.call_process_api(
  File "D:\OneDrive\Music\TTS\Applio-3.0.4\env\lib\site-packages\gradio\route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "D:\OneDrive\Music\TTS\Applio-3.0.4\env\lib\site-packages\gradio\blocks.py", line 1570, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "D:\OneDrive\Music\TTS\Applio-3.0.4\env\lib\site-packages\gradio\blocks.py", line 1456, in postprocess_data
    outputs_cached = processing_utils.move_files_to_cache(
  File "D:\OneDrive\Music\TTS\Applio-3.0.4\env\lib\site-packages\gradio\processing_utils.py", line 265, in move_files_to_cache
    return client_utils.traverse(data, _move_to_cache, client_utils.is_file_obj)
  File "D:\OneDrive\Music\TTS\Applio-3.0.4\env\lib\site-packages\gradio_client\utils.py", line 919, in traverse
    return func(json_obj)
  File "D:\OneDrive\Music\TTS\Applio-3.0.4\env\lib\site-packages\gradio\processing_utils.py", line 257, in _move_to_cache
    temp_file_path = move_resource_to_block_cache(payload.path, block)
  File "D:\OneDrive\Music\TTS\Applio-3.0.4\env\lib\site-packages\gradio\processing_utils.py", line 234, in move_resource_to_block_cache
    return block.move_resource_to_block_cache(url_or_file_path)
  File "D:\OneDrive\Music\TTS\Applio-3.0.4\env\lib\site-packages\gradio\blocks.py", line 258, in move_resource_to_block_cache
    temp_file_path = processing_utils.save_file_to_cache(
  File "D:\OneDrive\Music\TTS\Applio-3.0.4\env\lib\site-packages\gradio\processing_utils.py", line 170, in save_file_to_cache
    temp_dir = hash_file(file_path)
  File "D:\OneDrive\Music\TTS\Applio-3.0.4\env\lib\site-packages\gradio\processing_utils.py", line 102, in hash_file
    with open(file_path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\OneDrive\\Music\\TTS\\Applio-3.0.4\\assets\\audios\\tts_rvc_output.wav'
TTS with en-US-AvaNeural completed. Output TTS file: 'D:\OneDrive\Music\TTS\Applio-3.0.4\assets\audios\tts_output.wav'
Traceback (most recent call last):
  File "D:\OneDrive\Music\TTS\Applio-3.0.4\rvc\infer\infer.py", line 241, in <module>
    get_vc(model_path, 0)
  File "D:\OneDrive\Music\TTS\Applio-3.0.4\rvc\infer\infer.py", line 187, in get_vc
    cpt = torch.load(person, map_location="cpu")
  File "D:\OneDrive\Music\TTS\Applio-3.0.4\env\lib\site-packages\torch\serialization.py", line 986, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "D:\OneDrive\Music\TTS\Applio-3.0.4\env\lib\site-packages\torch\serialization.py", line 435, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "D:\OneDrive\Music\TTS\Applio-3.0.4\env\lib\site-packages\torch\serialization.py", line 416, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: ''
Traceback (most recent call last):
  File "D:\OneDrive\Music\TTS\Applio-3.0.4\env\lib\site-packages\gradio\queueing.py", line 495, in call_prediction
    output = await route_utils.call_process_api(
  File "D:\OneDrive\Music\TTS\Applio-3.0.4\env\lib\site-packages\gradio\route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "D:\OneDrive\Music\TTS\Applio-3.0.4\env\lib\site-packages\gradio\blocks.py", line 1570, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "D:\OneDrive\Music\TTS\Applio-3.0.4\env\lib\site-packages\gradio\blocks.py", line 1456, in postprocess_data
    outputs_cached = processing_utils.move_files_to_cache(
  File "D:\OneDrive\Music\TTS\Applio-3.0.4\env\lib\site-packages\gradio\processing_utils.py", line 265, in move_files_to_cache
    return client_utils.traverse(data, _move_to_cache, client_utils.is_file_obj)
  File "D:\OneDrive\Music\TTS\Applio-3.0.4\env\lib\site-packages\gradio_client\utils.py", line 919, in traverse
    return func(json_obj)
  File "D:\OneDrive\Music\TTS\Applio-3.0.4\env\lib\site-packages\gradio\processing_utils.py", line 257, in _move_to_cache
    temp_file_path = move_resource_to_block_cache(payload.path, block)
  File "D:\OneDrive\Music\TTS\Applio-3.0.4\env\lib\site-packages\gradio\processing_utils.py", line 234, in move_resource_to_block_cache
    return block.move_resource_to_block_cache(url_or_file_path)
  File "D:\OneDrive\Music\TTS\Applio-3.0.4\env\lib\site-packages\gradio\blocks.py", line 258, in move_resource_to_block_cache
    temp_file_path = processing_utils.save_file_to_cache(
  File "D:\OneDrive\Music\TTS\Applio-3.0.4\env\lib\site-packages\gradio\processing_utils.py", line 170, in save_file_to_cache
    temp_dir = hash_file(file_path)
  File "D:\OneDrive\Music\TTS\Applio-3.0.4\env\lib\site-packages\gradio\processing_utils.py", line 102, in hash_file
    with open(file_path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\OneDrive\\Music\\TTS\\Applio-3.0.4\\assets\\audios\\tts_rvc_output.wav'
TTS with en-US-AvaNeural completed. Output TTS file: 'D:\OneDrive\Music\TTS\Applio-3.0.4\assets\audios\tts_output.wav'
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001EA23B91790>
Traceback (most recent call last):
  File "D:\OneDrive\Music\TTS\Applio-3.0.4\env\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "D:\OneDrive\Music\TTS\Applio-3.0.4\env\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "D:\OneDrive\Music\TTS\Applio-3.0.4\env\lib\asyncio\base_events.py", line 751, in call_soon
    self._check_closed()
  File "D:\OneDrive\Music\TTS\Applio-3.0.4\env\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Traceback (most recent call last):
  File "D:\OneDrive\Music\TTS\Applio-3.0.4\rvc\infer\infer.py", line 241, in <module>
    get_vc(model_path, 0)
  File "D:\OneDrive\Music\TTS\Applio-3.0.4\rvc\infer\infer.py", line 187, in get_vc
    cpt = torch.load(person, map_location="cpu")
  File "D:\OneDrive\Music\TTS\Applio-3.0.4\env\lib\site-packages\torch\serialization.py", line 986, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "D:\OneDrive\Music\TTS\Applio-3.0.4\env\lib\site-packages\torch\serialization.py", line 435, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "D:\OneDrive\Music\TTS\Applio-3.0.4\env\lib\site-packages\torch\serialization.py", line 416, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: ''
Traceback (most recent call last):
  File "D:\OneDrive\Music\TTS\Applio-3.0.4\env\lib\site-packages\gradio\queueing.py", line 495, in call_prediction
    output = await route_utils.call_process_api(
  File "D:\OneDrive\Music\TTS\Applio-3.0.4\env\lib\site-packages\gradio\route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "D:\OneDrive\Music\TTS\Applio-3.0.4\env\lib\site-packages\gradio\blocks.py", line 1570, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "D:\OneDrive\Music\TTS\Applio-3.0.4\env\lib\site-packages\gradio\blocks.py", line 1456, in postprocess_data
    outputs_cached = processing_utils.move_files_to_cache(
  File "D:\OneDrive\Music\TTS\Applio-3.0.4\env\lib\site-packages\gradio\processing_utils.py", line 265, in move_files_to_cache
    return client_utils.traverse(data, _move_to_cache, client_utils.is_file_obj)
  File "D:\OneDrive\Music\TTS\Applio-3.0.4\env\lib\site-packages\gradio_client\utils.py", line 919, in traverse
    return func(json_obj)
  File "D:\OneDrive\Music\TTS\Applio-3.0.4\env\lib\site-packages\gradio\processing_utils.py", line 257, in _move_to_cache
    temp_file_path = move_resource_to_block_cache(payload.path, block)
  File "D:\OneDrive\Music\TTS\Applio-3.0.4\env\lib\site-packages\gradio\processing_utils.py", line 234, in move_resource_to_block_cache
    return block.move_resource_to_block_cache(url_or_file_path)
  File "D:\OneDrive\Music\TTS\Applio-3.0.4\env\lib\site-packages\gradio\blocks.py", line 258, in move_resource_to_block_cache
    temp_file_path = processing_utils.save_file_to_cache(
  File "D:\OneDrive\Music\TTS\Applio-3.0.4\env\lib\site-packages\gradio\processing_utils.py", line 170, in save_file_to_cache
    temp_dir = hash_file(file_path)
  File "D:\OneDrive\Music\TTS\Applio-3.0.4\env\lib\site-packages\gradio\processing_utils.py", line 102, in hash_file
    with open(file_path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\OneDrive\\Music\\TTS\\Applio-3.0.4\\assets\\audios\\tts_rvc_output.wav'

_------- on main drive

Traceback (most recent call last):
  File "C:\Users\SDS\Applio-3.0.4\env\lib\site-packages\httpcore\_exceptions.py", line 10, in map_exceptions
    yield
  File "C:\Users\SDS\Applio-3.0.4\env\lib\site-packages\httpcore\_backends\sync.py", line 168, in start_tls
    raise exc
  File "C:\Users\SDS\Applio-3.0.4\env\lib\site-packages\httpcore\_backends\sync.py", line 163, in start_tls
    sock = ssl_context.wrap_socket(
  File "C:\Users\SDS\Applio-3.0.4\env\lib\ssl.py", line 501, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\SDS\Applio-3.0.4\env\lib\ssl.py", line 1074, in _create
    self.do_handshake()
  File "C:\Users\SDS\Applio-3.0.4\env\lib\ssl.py", line 1343, in do_handshake
    self._sslobj.do_handshake()
socket.timeout: _ssl.c:1112: The handshake operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\SDS\Applio-3.0.4\env\lib\site-packages\httpx\_transports\default.py", line 67, in map_httpcore_exceptions
    yield
  File "C:\Users\SDS\Applio-3.0.4\env\lib\site-packages\httpx\_transports\default.py", line 231, in handle_request
    resp = self._pool.handle_request(req)
  File "C:\Users\SDS\Applio-3.0.4\env\lib\site-packages\httpcore\_sync\connection_pool.py", line 268, in handle_request
    raise exc
  File "C:\Users\SDS\Applio-3.0.4\env\lib\site-packages\httpcore\_sync\connection_pool.py", line 251, in handle_request
    response = connection.handle_request(request)
  File "C:\Users\SDS\Applio-3.0.4\env\lib\site-packages\httpcore\_sync\connection.py", line 99, in handle_request
    raise exc
  File "C:\Users\SDS\Applio-3.0.4\env\lib\site-packages\httpcore\_sync\connection.py", line 76, in handle_request
    stream = self._connect(request)
  File "C:\Users\SDS\Applio-3.0.4\env\lib\site-packages\httpcore\_sync\connection.py", line 156, in _connect
    stream = stream.start_tls(**kwargs)
  File "C:\Users\SDS\Applio-3.0.4\env\lib\site-packages\httpcore\_backends\sync.py", line 168, in start_tls
    raise exc
  File "C:\Users\SDS\Applio-3.0.4\env\lib\contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\SDS\Applio-3.0.4\env\lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectTimeout: _ssl.c:1112: The handshake operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\SDS\Applio-3.0.4\env\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "C:\Users\SDS\Applio-3.0.4\env\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\SDS\Applio-3.0.4\env\lib\site-packages\gradio\analytics.py", line 61, in _do_normal_analytics_request
    data["ip_address"] = get_local_ip_address()
  File "C:\Users\SDS\Applio-3.0.4\env\lib\site-packages\gradio\analytics.py", line 117, in get_local_ip_address
    ip_address = httpx.get(
  File "C:\Users\SDS\Applio-3.0.4\env\lib\site-packages\httpx\_api.py", line 196, in get
    return request(
  File "C:\Users\SDS\Applio-3.0.4\env\lib\site-packages\httpx\_api.py", line 104, in request
    return client.request(
  File "C:\Users\SDS\Applio-3.0.4\env\lib\site-packages\httpx\_client.py", line 828, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "C:\Users\SDS\Applio-3.0.4\env\lib\site-packages\httpx\_client.py", line 915, in send
    response = self._send_handling_auth(
  File "C:\Users\SDS\Applio-3.0.4\env\lib\site-packages\httpx\_client.py", line 943, in _send_handling_auth
    response = self._send_handling_redirects(
  File "C:\Users\SDS\Applio-3.0.4\env\lib\site-packages\httpx\_client.py", line 980, in _send_handling_redirects
    response = self._send_single_request(request)
  File "C:\Users\SDS\Applio-3.0.4\env\lib\site-packages\httpx\_client.py", line 1016, in _send_single_request
    response = transport.handle_request(request)
  File "C:\Users\SDS\Applio-3.0.4\env\lib\site-packages\httpx\_transports\default.py", line 231, in handle_request
    resp = self._pool.handle_request(req)
  File "C:\Users\SDS\Applio-3.0.4\env\lib\contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\SDS\Applio-3.0.4\env\lib\site-packages\httpx\_transports\default.py", line 84, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectTimeout: _ssl.c:1112: The handshake operation timed out
TTS with af-ZA-WillemNeural completed. Output TTS file: 'C:\Users\SDS\Applio-3.0.4\assets\audios\tts_output.wav'
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000266B4AE44C0>
Traceback (most recent call last):
  File "C:\Users\SDS\Applio-3.0.4\env\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\SDS\Applio-3.0.4\env\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\SDS\Applio-3.0.4\env\lib\asyncio\base_events.py", line 751, in call_soon
    self._check_closed()
  File "C:\Users\SDS\Applio-3.0.4\env\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Traceback (most recent call last):
  File "C:\Users\SDS\Applio-3.0.4\rvc\infer\infer.py", line 241, in <module>
    get_vc(model_path, 0)
  File "C:\Users\SDS\Applio-3.0.4\rvc\infer\infer.py", line 187, in get_vc
    cpt = torch.load(person, map_location="cpu")
  File "C:\Users\SDS\Applio-3.0.4\env\lib\site-packages\torch\serialization.py", line 986, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "C:\Users\SDS\Applio-3.0.4\env\lib\site-packages\torch\serialization.py", line 435, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "C:\Users\SDS\Applio-3.0.4\env\lib\site-packages\torch\serialization.py", line 416, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: ''
Traceback (most recent call last):
  File "C:\Users\SDS\Applio-3.0.4\env\lib\site-packages\gradio\queueing.py", line 495, in call_prediction
    output = await route_utils.call_process_api(
  File "C:\Users\SDS\Applio-3.0.4\env\lib\site-packages\gradio\route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\SDS\Applio-3.0.4\env\lib\site-packages\gradio\blocks.py", line 1570, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\SDS\Applio-3.0.4\env\lib\site-packages\gradio\blocks.py", line 1456, in postprocess_data
    outputs_cached = processing_utils.move_files_to_cache(
  File "C:\Users\SDS\Applio-3.0.4\env\lib\site-packages\gradio\processing_utils.py", line 265, in move_files_to_cache
    return client_utils.traverse(data, _move_to_cache, client_utils.is_file_obj)
  File "C:\Users\SDS\Applio-3.0.4\env\lib\site-packages\gradio_client\utils.py", line 919, in traverse
    return func(json_obj)
  File "C:\Users\SDS\Applio-3.0.4\env\lib\site-packages\gradio\processing_utils.py", line 257, in _move_to_cache
    temp_file_path = move_resource_to_block_cache(payload.path, block)
  File "C:\Users\SDS\Applio-3.0.4\env\lib\site-packages\gradio\processing_utils.py", line 234, in move_resource_to_block_cache
    return block.move_resource_to_block_cache(url_or_file_path)
  File "C:\Users\SDS\Applio-3.0.4\env\lib\site-packages\gradio\blocks.py", line 258, in move_resource_to_block_cache
    temp_file_path = processing_utils.save_file_to_cache(
  File "C:\Users\SDS\Applio-3.0.4\env\lib\site-packages\gradio\processing_utils.py", line 170, in save_file_to_cache
    temp_dir = hash_file(file_path)
  File "C:\Users\SDS\Applio-3.0.4\env\lib\site-packages\gradio\processing_utils.py", line 102, in hash_file
    with open(file_path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\SDS\\Applio-3.0.4\\assets\\audios\\tts_rvc_output.wa

**Comment by aitronssesin** [comment]
Do not install applio in the D: drive install it in the C: drive

**Comment by planetrenox** [comment]
same happens in C drive. is it because no voice is selected? the process to download voices does not work

**Comment by Nevoet** [comment]
It doesnt matter if its installed on D: or C:, the error is the same anyway. Just updated to latest version and this started to happen. The process is looking for the file "tts_rvc_output.wav" thats not being created.
