### ISSUE TITLE
File contains no section headers.[BUG]

### ISSUE THREAD

**Issue by Dyo-Anima** [IAHispano/Applio#273]
**Describe the bug**
it does not work, it gives this error when starting run-applio.bat

(base) E:\MachineLearning\Applio>E:\MachineLearning\Applio\run-applio.bat
Traceback (most recent call last):
  File "E:\MachineLearning\Applio\app.py", line 1, in <module>
    import gradio as gr
  File "E:\MachineLearning\Applio\env\lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio._simple_templates
  File "E:\MachineLearning\Applio\env\lib\site-packages\gradio\_simple_templates\__init__.py", line 1, in <module>
    from .simpledropdown import SimpleDropdown
  File "E:\MachineLearning\Applio\env\lib\site-packages\gradio\_simple_templates\simpledropdown.py", line 6, in <module>    from gradio.components.base import FormComponent
  File "E:\MachineLearning\Applio\env\lib\site-packages\gradio\components\__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "E:\MachineLearning\Applio\env\lib\site-packages\gradio\components\annotated_image.py", line 8, in <module>
    from gradio_client.documentation import document, set_documentation_group
  File "E:\MachineLearning\Applio\env\lib\site-packages\gradio_client\__init__.py", line 1, in <module>
    from gradio_client.client import Client
  File "E:\MachineLearning\Applio\env\lib\site-packages\gradio_client\client.py", line 25, in <module>
    from huggingface_hub import CommitOperationAdd, SpaceHardware, SpaceStage
  File "<frozen importlib._bootstrap>", line 1055, in _handle_fromlist
  File "E:\MachineLearning\Applio\env\lib\site-packages\huggingface_hub\__init__.py", line 370, in __getattr__
    submod = importlib.import_module(submod_path)
  File "E:\MachineLearning\Applio\env\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "E:\MachineLearning\Applio\env\lib\site-packages\huggingface_hub\hf_api.py", line 62, in <module>
    from ._inference_endpoints import InferenceEndpoint, InferenceEndpointType
  File "E:\MachineLearning\Applio\env\lib\site-packages\huggingface_hub\_inference_endpoints.py", line 7, in <module>
    from .inference._client import InferenceClient
  File "E:\MachineLearning\Applio\env\lib\site-packages\huggingface_hub\inference\_client.py", line 56, in <module>
    from huggingface_hub.inference._common import (
  File "E:\MachineLearning\Applio\env\lib\site-packages\huggingface_hub\inference\_common.py", line 51, in <module>
    from ._text_generation import TextGenerationStreamResponse, _parse_text_generation_error
  File "E:\MachineLearning\Applio\env\lib\site-packages\huggingface_hub\inference\_text_generation.py", line 60, in <module>
    class TextGenerationParameters:
  File "E:\MachineLearning\Applio\env\lib\site-packages\pydantic\dataclasses.py", line 250, in dataclass
    return create_dataclass(_cls)
  File "E:\MachineLearning\Applio\env\lib\site-packages\pydantic\dataclasses.py", line 241, in create_dataclass
    pydantic_complete = _pydantic_dataclasses.complete_dataclass(
  File "E:\MachineLearning\Applio\env\lib\site-packages\pydantic\_internal\_dataclasses.py", line 175, in complete_dataclass
    cls.__pydantic_validator__ = validator = create_schema_validator(
  File "E:\MachineLearning\Applio\env\lib\site-packages\pydantic\plugin\_schema_validator.py", line 37, in create_schema_validator
    plugins = get_plugins()
  File "E:\MachineLearning\Applio\env\lib\site-packages\pydantic\plugin\_loader.py", line 35, in get_plugins
    for entry_point in dist.entry_points:
  File "E:\MachineLearning\Applio\env\lib\importlib\metadata.py", line 270, in entry_points
    return EntryPoint._from_text(self.read_text('entry_points.txt'))
  File "E:\MachineLearning\Applio\env\lib\importlib\metadata.py", line 119, in _from_text
    config.read_string(text)
  File "E:\MachineLearning\Applio\env\lib\configparser.py", line 723, in read_string
    self.read_file(sfile, source)
  File "E:\MachineLearning\Applio\env\lib\configparser.py", line 718, in read_file
    self._read(f, source)
  File "E:\MachineLearning\Applio\env\lib\configparser.py", line 1085, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
configparser.MissingSectionHeaderError: File contains no section headers.
file: '<string>', line: 1
'estimator_ckpt_converter =tensorflow_estimator.python.estimator.tools.checkpoint_converter:principal\n'
Presione una tecla para continuar . . .

**To Reproduce**
1.  start run-applio.bat

**Expected behavior**
to function properly

**Assets**
If applicable, add screenshots/videos to help explain your problem.

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser none
 - GPU:RTX4070ti

**Additional context**
To add more context, the installation was completed correctly.

**Comment by Dyo-Anima** [comment]
I just fixed it, it worked, it turns out it was conflicting with another instance of python that I had in 
C:\Users\myuser\AppData\Roaming\Python\Python39\site-packages\
