### ISSUE TITLE
[BUG]getting an error when trying to use Inference feature

### ISSUE THREAD

**Issue by Lolsu32** [IAHispano/Applio#297]
Tried to use Inference, it would only give me an error message no matter what I tried, and I don't understand the error message.

"GET was unable to find an engine to execute this computation
Voice conversion failed: cannot unpack non-iterable NoneType object
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\Applio-3.0.7\env\lib\site-packages\gradio\queueing.py", line 495, in call_prediction
    output = await route_utils.call_process_api(
  File "C:\Users\Admin\Desktop\Applio-3.0.7\env\lib\site-packages\gradio\route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\Admin\Desktop\Applio-3.0.7\env\lib\site-packages\gradio\blocks.py", line 1570, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\Admin\Desktop\Applio-3.0.7\env\lib\site-packages\gradio\blocks.py", line 1456, in postprocess_data
    outputs_cached = processing_utils.move_files_to_cache(
  File "C:\Users\Admin\Desktop\Applio-3.0.7\env\lib\site-packages\gradio\processing_utils.py", line 265, in move_files_to_cache
    return client_utils.traverse(data, _move_to_cache, client_utils.is_file_obj)
  File "C:\Users\Admin\Desktop\Applio-3.0.7\env\lib\site-packages\gradio_client\utils.py", line 919, in traverse
    return func(json_obj)
  File "C:\Users\Admin\Desktop\Applio-3.0.7\env\lib\site-packages\gradio\processing_utils.py", line 257, in _move_to_cache
    temp_file_path = move_resource_to_block_cache(payload.path, block)
  File "C:\Users\Admin\Desktop\Applio-3.0.7\env\lib\site-packages\gradio\processing_utils.py", line 234, in move_resource_to_block_cache
    return block.move_resource_to_block_cache(url_or_file_path)
  File "C:\Users\Admin\Desktop\Applio-3.0.7\env\lib\site-packages\gradio\blocks.py", line 258, in move_resource_to_block_cache
    temp_file_path = processing_utils.save_file_to_cache(
  File "C:\Users\Admin\Desktop\Applio-3.0.7\env\lib\site-packages\gradio\processing_utils.py", line 170, in save_file_to_cache
    temp_dir = hash_file(file_path)
  File "C:\Users\Admin\Desktop\Applio-3.0.7\env\lib\site-packages\gradio\processing_utils.py", line 102, in hash_file
    with open(file_path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Admin\\Desktop\\Applio-3.0.7\\assets\\audios\\zelda1vocals_output.wav'

The audio is called zelda1vocals.wav

TTS seems to work just fine using the same model, so I don't get what the problem is.

I'm using Firefox on a Windows 10 PC

**Comment by MystyTom** [comment]
Currently facing the same issue rn, Any ideas?

**Comment by blaise-tk** [comment]
Duplicated, move there. https://github.com/IAHispano/Applio/issues/214
