### ISSUE TITLE
TTS ERROR

### ISSUE THREAD

**Issue by RenamonAR** [IAHispano/Applio#339]
Hello! 

I have tried generating audio from text using the es-AR-TomasNeural voice and a voice model that I have downloaded. When I hit generate, it processes for five seconds and then throws an error. I attach everything that happened in the console.

```
Theme Loaded: Applio
Running on local URL:  http://127.0.0.1:6969

To create a public link, set `share=True` in `launch()`.
TTS with es-AR-TomasNeural completed. Output TTS file: 'C:\ApplioV3.0.8compiladp\ApplioV3.0.8\assets\audios\tts_output.wav'
Traceback (most recent call last):
  File "C:\ApplioV3.0.8compiladp\ApplioV3.0.8\rvc\infer\infer.py", line 9, in <module>
    from pipeline import VC
  File "C:\ApplioV3.0.8compiladp\ApplioV3.0.8\rvc\infer\pipeline.py", line 4, in <module>
    import torchcrepe
  File "C:\ApplioV3.0.8compiladp\ApplioV3.0.8\env\lib\site-packages\torchcrepe\__init__.py", line 1, in <module>
    from . import decode
  File "C:\ApplioV3.0.8compiladp\ApplioV3.0.8\env\lib\site-packages\torchcrepe\decode.py", line 1, in <module>
    import librosa
  File "C:\ApplioV3.0.8compiladp\ApplioV3.0.8\env\lib\site-packages\librosa\__init__.py", line 211, in <module>
    from . import decompose
  File "C:\ApplioV3.0.8compiladp\ApplioV3.0.8\env\lib\site-packages\librosa\decompose.py", line 19, in <module>
    import sklearn.decomposition
  File "C:\ApplioV3.0.8compiladp\ApplioV3.0.8\env\lib\site-packages\sklearn\__init__.py", line 83, in <module>
    from . import (
  File "C:\ApplioV3.0.8compiladp\ApplioV3.0.8\env\lib\site-packages\sklearn\_distributor_init.py", line 21, in <module>
    WinDLL(op.abspath(vcomp140_dll_filename))
  File "C:\ApplioV3.0.8compiladp\ApplioV3.0.8\env\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'C:\ApplioV3.0.8compiladp\ApplioV3.0.8\env\lib\site-packages\sklearn\.libs\vcomp140.dll' (or one of its dependencies). Try using the full path with constructor syntax.
Traceback (most recent call last):
  File "C:\ApplioV3.0.8compiladp\ApplioV3.0.8\env\lib\site-packages\gradio\queueing.py", line 495, in call_prediction
    output = await route_utils.call_process_api(
  File "C:\ApplioV3.0.8compiladp\ApplioV3.0.8\env\lib\site-packages\gradio\route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\ApplioV3.0.8compiladp\ApplioV3.0.8\env\lib\site-packages\gradio\blocks.py", line 1570, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\ApplioV3.0.8compiladp\ApplioV3.0.8\env\lib\site-packages\gradio\blocks.py", line 1456, in postprocess_data
    outputs_cached = processing_utils.move_files_to_cache(
  File "C:\ApplioV3.0.8compiladp\ApplioV3.0.8\env\lib\site-packages\gradio\processing_utils.py", line 265, in move_files_to_cache
    return client_utils.traverse(data, _move_to_cache, client_utils.is_file_obj)
  File "C:\ApplioV3.0.8compiladp\ApplioV3.0.8\env\lib\site-packages\gradio_client\utils.py", line 919, in traverse
    return func(json_obj)
  File "C:\ApplioV3.0.8compiladp\ApplioV3.0.8\env\lib\site-packages\gradio\processing_utils.py", line 257, in _move_to_cache
    temp_file_path = move_resource_to_block_cache(payload.path, block)
  File "C:\ApplioV3.0.8compiladp\ApplioV3.0.8\env\lib\site-packages\gradio\processing_utils.py", line 234, in move_resource_to_block_cache
    return block.move_resource_to_block_cache(url_or_file_path)
  File "C:\ApplioV3.0.8compiladp\ApplioV3.0.8\env\lib\site-packages\gradio\blocks.py", line 258, in move_resource_to_block_cache
    temp_file_path = processing_utils.save_file_to_cache(
  File "C:\ApplioV3.0.8compiladp\ApplioV3.0.8\env\lib\site-packages\gradio\processing_utils.py", line 170, in save_file_to_cache
    temp_dir = hash_file(file_path)
  File "C:\ApplioV3.0.8compiladp\ApplioV3.0.8\env\lib\site-packages\gradio\processing_utils.py", line 102, in hash_file
    with open(file_path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\ApplioV3.0.8compiladp\\ApplioV3.0.8\\assets\\audios\\tts_rvc_output.wav'
```

What could be happening?

**Comment by blaise-tk** [comment]
https://github.com/IAHispano/Applio/issues/214#issuecomment-1986421084
