### ISSUE TITLE
[BUG] TTS/Infer not found error.

### ISSUE THREAD

**Issue by sanjuhs** [IAHispano/Applio#344]
**Bug Description**
Getting a file not found erro, checked in Chatgpt as well, not sure what exactly needs to be changed.

**Steps to Reproduce**
Outline the steps to replicate the issue:
1. Installed the latest version of the applio release
2. tried to do simple TTS with preloaded voices , also downloaded some RVC voices, 
3. pressed the convert button and getting error and the following error
4. Observe the error.

**Expected Behavior**
I had hoped it would work easily with an audio clip being generated.

**Assets**
Include screenshots or videos if they can illustrate the issue.

**Desktop Details:**
- Operating System: Windows 11
- Browser: Chrome
- NVDIA GPU 3060
- 

**Additional Context**
Any additional information that might be relevant to the issue.

TTS with ar-BH-LailaNeural completed. Output TTS file: 'C:\Users\USER\Desktop\aiTools\Audio\Applio-3.0.8\assets\audios\tts_output.wav'
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000262B6C9AC10>
Traceback (most recent call last):
  File "C:\Users\USER\Desktop\aiTools\Audio\Applio-3.0.8\env\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\USER\Desktop\aiTools\Audio\Applio-3.0.8\env\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\USER\Desktop\aiTools\Audio\Applio-3.0.8\env\lib\asyncio\base_events.py", line 751, in call_soon
    self._check_closed()
  File "C:\Users\USER\Desktop\aiTools\Audio\Applio-3.0.8\env\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Traceback (most recent call last):
  File "C:\Users\USER\Desktop\aiTools\Audio\Applio-3.0.8\rvc\infer\infer.py", line 251, in <module>
    get_vc(model_path, 0)
  File "C:\Users\USER\Desktop\aiTools\Audio\Applio-3.0.8\rvc\infer\infer.py", line 208, in get_vc
    cpt = torch.load(person, map_location="cpu")
  File "C:\Users\USER\Desktop\aiTools\Audio\Applio-3.0.8\env\lib\site-packages\torch\serialization.py", line 986, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "C:\Users\USER\Desktop\aiTools\Audio\Applio-3.0.8\env\lib\site-packages\torch\serialization.py", line 435, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "C:\Users\USER\Desktop\aiTools\Audio\Applio-3.0.8\env\lib\site-packages\torch\serialization.py", line 416, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: ''
Traceback (most recent call last):
  File "C:\Users\USER\Desktop\aiTools\Audio\Applio-3.0.8\env\lib\site-packages\gradio\queueing.py", line 495, in call_prediction
    output = await route_utils.call_process_api(
  File "C:\Users\USER\Desktop\aiTools\Audio\Applio-3.0.8\env\lib\site-packages\gradio\route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\USER\Desktop\aiTools\Audio\Applio-3.0.8\env\lib\site-packages\gradio\blocks.py", line 1570, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\USER\Desktop\aiTools\Audio\Applio-3.0.8\env\lib\site-packages\gradio\blocks.py", line 1456, in postprocess_data
    outputs_cached = processing_utils.move_files_to_cache(
  File "C:\Users\USER\Desktop\aiTools\Audio\Applio-3.0.8\env\lib\site-packages\gradio\processing_utils.py", line 265, in move_files_to_cache
    return client_utils.traverse(data, _move_to_cache, client_utils.is_file_obj)
  File "C:\Users\USER\Desktop\aiTools\Audio\Applio-3.0.8\env\lib\site-packages\gradio_client\utils.py", line 919, in traverse
    return func(json_obj)
  File "C:\Users\USER\Desktop\aiTools\Audio\Applio-3.0.8\env\lib\site-packages\gradio\processing_utils.py", line 257, in _move_to_cache
    temp_file_path = move_resource_to_block_cache(payload.path, block)
  File "C:\Users\USER\Desktop\aiTools\Audio\Applio-3.0.8\env\lib\site-packages\gradio\processing_utils.py", line 234, in move_resource_to_block_cache
    return block.move_resource_to_block_cache(url_or_file_path)
  File "C:\Users\USER\Desktop\aiTools\Audio\Applio-3.0.8\env\lib\site-packages\gradio\blocks.py", line 258, in move_resource_to_block_cache
    temp_file_path = processing_utils.save_file_to_cache(
  File "C:\Users\USER\Desktop\aiTools\Audio\Applio-3.0.8\env\lib\site-packages\gradio\processing_utils.py", line 170, in save_file_to_cache
    temp_dir = hash_file(file_path)
  File "C:\Users\USER\Desktop\aiTools\Audio\Applio-3.0.8\env\lib\site-packages\gradio\processing_utils.py", line 102, in hash_file
    with open(file_path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\USER\\Desktop\\aiTools\\Audio\\Applio-3.0.8\\assets\\audios\\tts_rvc_output.wav'
![image](https://github.com/IAHispano/Applio/assets/56527659/4615b960-be90-4afd-ae86-df044815a8bf)

**Comment by aitronssesin** [comment]
Is the same error happening in the latest 3.1.1 version of applio?

**Comment by sanjuhs** [comment]
yes its working properly in the latest version thnak you
