### ISSUE TITLE
Error while using TTS

### ISSUE THREAD

**Issue by skaba04** [IAHispano/Applio#355]
**Bug Description**
I get this erorr while using TTS

**Steps to Reproduce**
While using TTS thie error happened
Traceback (most recent call last):
  File "E:\AI\VoiceUI\Applio-3.0.2\Applio\rvc\infer\infer.py", line 9, in <module>
    from pipeline import VC
  File "E:\AI\VoiceUI\Applio-3.0.2\Applio\rvc\infer\pipeline.py", line 17, in <module>
    from rvc.lib.FCPEF0Predictor import FCPEF0Predictor
  File "E:\AI\VoiceUI\Applio-3.0.2\Applio\rvc\lib\FCPEF0Predictor.py", line 17, in <module>
    from einops import rearrange, repeat
ModuleNotFoundError: No module named 'einops'
Traceback (most recent call last):
  File "E:\AI\VoiceUI\Applio-3.0.2\Applio\env\lib\site-packages\gradio\queueing.py", line 495, in call_prediction
    output = await route_utils.call_process_api(
  File "E:\AI\VoiceUI\Applio-3.0.2\Applio\env\lib\site-packages\gradio\route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "E:\AI\VoiceUI\Applio-3.0.2\Applio\env\lib\site-packages\gradio\blocks.py", line 1570, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "E:\AI\VoiceUI\Applio-3.0.2\Applio\env\lib\site-packages\gradio\blocks.py", line 1456, in postprocess_data
    outputs_cached = processing_utils.move_files_to_cache(
  File "E:\AI\VoiceUI\Applio-3.0.2\Applio\env\lib\site-packages\gradio\processing_utils.py", line 265, in move_files_to_cache
    return client_utils.traverse(data, _move_to_cache, client_utils.is_file_obj)
  File "E:\AI\VoiceUI\Applio-3.0.2\Applio\env\lib\site-packages\gradio_client\utils.py", line 919, in traverse
    return func(json_obj)
  File "E:\AI\VoiceUI\Applio-3.0.2\Applio\env\lib\site-packages\gradio\processing_utils.py", line 257, in _move_to_cache
    temp_file_path = move_resource_to_block_cache(payload.path, block)
  File "E:\AI\VoiceUI\Applio-3.0.2\Applio\env\lib\site-packages\gradio\processing_utils.py", line 234, in move_resource_to_block_cache
    return block.move_resource_to_block_cache(url_or_file_path)
  File "E:\AI\VoiceUI\Applio-3.0.2\Applio\env\lib\site-packages\gradio\blocks.py", line 258, in move_resource_to_block_cache
    temp_file_path = processing_utils.save_file_to_cache(
  File "E:\AI\VoiceUI\Applio-3.0.2\Applio\env\lib\site-packages\gradio\processing_utils.py", line 170, in save_file_to_cache
    temp_dir = hash_file(file_path)
  File "E:\AI\VoiceUI\Applio-3.0.2\Applio\env\lib\site-packages\gradio\processing_utils.py", line 102, in hash_file
    with open(file_path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\AI\\VoiceUI\\Applio-3.0.2\\Applio\\assets\\audios\\tts_rvc_output.wav

4. Observe the error.

**Expected Behavior**
be alble to see the coverted speech

**Assets**
Include screenshots or videos if they can illustrate the issue.

**Desktop Details:**
- Windows 10
- Browser: Opera GX

**Comment by skaba04** [comment]
[Error applio.txt](https://github.com/IAHispano/Applio/files/14628418/Error.applio.txt)

**Comment by blaise-tk** [comment]
already answered on discord
