### ISSUE TITLE
Error when load italia pretrain(https://huggingface.co/TheStinger/itaila)[BUG]

### ISSUE THREAD

**Issue by CNMajest** [IAHispano/Applio#382]
Loaded pretrained_G D:\Applio-3.1.1\logs\ItaliaPreT\ItaIla_32k_G.pth
Process Process-1:
Traceback (most recent call last):
  File "D:\Applio-3.1.1\rvc\train\train.py", line 205, in run
    latest_checkpoint_path(hps.model_dir, "D_*.pth"), net_d, optim_d
  File "D:\Applio-3.1.1\rvc\train\utils.py", line 86, in latest_checkpoint_path
    x = f_list[-1]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Applio-3.1.1\env\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "D:\Applio-3.1.1\env\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Applio-3.1.1\rvc\train\train.py", line 220, in run
    net_g.module.load_state_dict(
  File "D:\Applio-3.1.1\env\lib\site-packages\torch\nn\modules\module.py", line 2152, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for SynthesizerTrnMs768NSFsid:
        size mismatch for dec.noise_convs.0.weight: copying a param with shape torch.Size([256, 1, 64]) from checkpoint, the shape in current model is torch.Size([256, 1, 80]).
        size mismatch for dec.ups.0.parametrizations.weight.original1: copying a param with shape torch.Size([512, 256, 20]) from checkpoint, the shape in current model is torch.Size([512, 256, 24]).
        size mismatch for dec.ups.1.parametrizations.weight.original1: copying a param with shape torch.Size([256, 128, 16]) from checkpoint, the shape in current model is torch.Size([256, 128, 20]).
        size mismatch for enc_q.pre.weight: copying a param with shape torch.Size([192, 513, 1]) from checkpoint, the shape in current model is torch.Size([192, 1025, 1]).

**Comment by CNMajest** [comment]
i used sampling rate 32k pretrain as 48k, that's why the error is...
