### ISSUE TITLE
[BUG]: 3.1.1 version TTS does not work

### ISSUE THREAD

**Issue by skaba04** [IAHispano/Applio#383]
**Bug Description**
Please provide a clear and concise description of the bug.

Error while using TTS:

Traceback (most recent call last):
  File "E:\AI\VoiceUI\Applio\ApplioV3.1.1\env\lib\site-packages\gradio\queueing.py", line 495, in call_prediction
    output = await route_utils.call_process_api(
  File "E:\AI\VoiceUI\Applio\ApplioV3.1.1\env\lib\site-packages\gradio\route_utils.py", line 230, in call_process_api
    output = await app.get_blocks().process_api(
  File "E:\AI\VoiceUI\Applio\ApplioV3.1.1\env\lib\site-packages\gradio\blocks.py", line 1599, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "E:\AI\VoiceUI\Applio\ApplioV3.1.1\env\lib\site-packages\gradio\blocks.py", line 1453, in postprocess_data
    outputs_cached = processing_utils.move_files_to_cache(
  File "E:\AI\VoiceUI\Applio\ApplioV3.1.1\env\lib\site-packages\gradio\processing_utils.py", line 267, in move_files_to_cache
    return client_utils.traverse(data, _move_to_cache, client_utils.is_file_obj)
  File "E:\AI\VoiceUI\Applio\ApplioV3.1.1\env\lib\site-packages\gradio_client\utils.py", line 981, in traverse
    return func(json_obj)
  File "E:\AI\VoiceUI\Applio\ApplioV3.1.1\env\lib\site-packages\gradio\processing_utils.py", line 259, in _move_to_cache
    temp_file_path = move_resource_to_block_cache(payload.path, block)
  File "E:\AI\VoiceUI\Applio\ApplioV3.1.1\env\lib\site-packages\gradio\processing_utils.py", line 236, in move_resource_to_block_cache
    return block.move_resource_to_block_cache(url_or_file_path)
  File "E:\AI\VoiceUI\Applio\ApplioV3.1.1\env\lib\site-packages\gradio\blocks.py", line 257, in move_resource_to_block_cache
    temp_file_path = processing_utils.save_file_to_cache(
  File "E:\AI\VoiceUI\Applio\ApplioV3.1.1\env\lib\site-packages\gradio\processing_utils.py", line 170, in save_file_to_cache
**Assets**

Include screenshots or videos if they can illustrate the issue.
![image](https://github.com/IAHispano/Applio/assets/116293460/382ae635-e11c-4444-a41a-fb15a8261f2a)

**Desktop Details:**
- Operating System: Windows 10
- Browser: Opera GX

**Comment by aitronssesin** [comment]
Try installing applio in the C: drive

![Applio only in C: drive](https://github.com/IAHispano/Applio/assets/74368135/c26ae722-b194-4f22-967b-086749038d47)

**Comment by skaba04** [comment]
> Try installing applio in the C: drive
> 
> ![Applio only in C: drive](https://private-user-images.githubusercontent.com/74368135/319746616-c26ae722-b194-4f22-967b-086749038d47.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyNTk2NzAsIm5iZiI6MTcxMjI1OTM3MCwicGF0aCI6Ii83NDM2ODEzNS8zMTk3NDY2MTYtYzI2YWU3MjItYjE5NC00ZjIyLTk2N2ItMDg2NzQ5MDM4ZDQ3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA0VDE5MzYxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxYWE2ZjNmNzUzZGQ5MjBiY2Q5M2M0MThlZTFjMGVkZTgyZTM1Yjg1NjY2YWIyOWU0YTc3NTQyYTlmNTYwNDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AEDSrdCig1Kh8qMPPKkf9RYNnb-0nnQjQuGBwJ6snoQ)

I don't have enough space on C: drive

**Comment by aitronssesin** [comment]
That's a big problem because you will have some other issues with different software.
