### ISSUE TITLE
[BUG] No such file or directory

### ISSUE THREAD

**Issue by cjmaxik** [IAHispano/Applio#397]
**Bug Description**
There is no output from inference, it leads to an error `No such file or directory`.

**Steps to Reproduce**
1. Go to 'Inference' tab
2. Choose the Voice Model and Index File
3. Upload a file
4. Click 'Convert'

**Expected Behavior**
The converted file appears in the folder.

**Desktop Details:**
- Ubuntu 22.04.4 LTS via WSL
- Chrome v124

**Logs**
```
<All keys matched successfully>
module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
Conversion completed. Output file: 'assets/audios/file_output.wav' in 4.62 seconds.
Traceback (most recent call last):
  File "/home/cjmaxik/Applio/.venv/lib/python3.10/site-packages/gradio/queueing.py", line 495, in call_prediction
    output = await route_utils.call_process_api(
  File "/home/cjmaxik/Applio/.venv/lib/python3.10/site-packages/gradio/route_utils.py", line 230, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/cjmaxik/Applio/.venv/lib/python3.10/site-packages/gradio/blocks.py", line 1599, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/home/cjmaxik/Applio/.venv/lib/python3.10/site-packages/gradio/blocks.py", line 1453, in postprocess_data
    outputs_cached = processing_utils.move_files_to_cache(
  File "/home/cjmaxik/Applio/.venv/lib/python3.10/site-packages/gradio/processing_utils.py", line 267, in move_files_to_cache
    return client_utils.traverse(data, _move_to_cache, client_utils.is_file_obj)
  File "/home/cjmaxik/Applio/.venv/lib/python3.10/site-packages/gradio_client/utils.py", line 981, in traverse
    return func(json_obj)
  File "/home/cjmaxik/Applio/.venv/lib/python3.10/site-packages/gradio/processing_utils.py", line 259, in _move_to_cache
    temp_file_path = move_resource_to_block_cache(payload.path, block)
  File "/home/cjmaxik/Applio/.venv/lib/python3.10/site-packages/gradio/processing_utils.py", line 236, in move_resource_to_block_cache
    return block.move_resource_to_block_cache(url_or_file_path)
  File "/home/cjmaxik/Applio/.venv/lib/python3.10/site-packages/gradio/blocks.py", line 257, in move_resource_to_block_cache
    temp_file_path = processing_utils.save_file_to_cache(
  File "/home/cjmaxik/Applio/.venv/lib/python3.10/site-packages/gradio/processing_utils.py", line 170, in save_file_to_cache
    temp_dir = hash_file(file_path)
  File "/home/cjmaxik/Applio/.venv/lib/python3.10/site-packages/gradio/processing_utils.py", line 102, in hash_file
    with open(file_path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/cjmaxik/Applio/assets/audios/file_output.wav'
```

**Comment by cjmaxik** [comment]
Works after installing Python requirements again manually within a Python environment.
