### ISSUE TITLE
[BUG] IndexError: list index out of range

### ISSUE THREAD

**Issue by Maitresinh** [IAHispano/Applio#463]
**Bug Description**
Error when importing a voice model. The voice appears in the list, but don't seems to work

**Steps to Reproduce**

Import a voice modele from applio, using link or importing. 
Show "erreur". 
In the logs :
```

index -1 is out of bounds for axis 0 with size 0
Conversion completed. Output file: 'assets\audios\armand_output.wav' in 3.91 seconds.
[{'id_': 'ded58405ae-45f3f-7o3r54e65330', 'name': 'Francis Cabrel - (1977 - 1985)', 'link': 'https://drive.google.com/file/d/1-0j6tQCn5IBis5gUb6fg43Dc36DB07on/view?usp=sharing', 'epochs': '300', 'type': 'RVC', 'algorithm': 'Rmvpe', 'image_url': 'https://cdn.discordapp.com/attachments/1141026159627354113/1141026159983861811/1481347-francis-cabrel-malgre-ses-plus-de-20-580x0-3.png', 'id': '1141026159627354113', 'author_id': '380844293822349312', 'created_at': '2023-08-24T00:00:00.000000+00:00', 'likes': '0', 'author_username': 'jojo76ytb', 'server_id': '1.1284161785875702e+18', 'server_name': 'Unknown', 'tags': 'Singer'}]
Proceeding with the extraction...
Traceback (most recent call last):
  File "C:\non-install\ApplioV3.2.0\env\lib\site-packages\gradio\queueing.py", line 528, in process_events
    response = await route_utils.call_process_api(
  File "C:\non-install\ApplioV3.2.0\env\lib\site-packages\gradio\route_utils.py", line 270, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\non-install\ApplioV3.2.0\env\lib\site-packages\gradio\blocks.py", line 1908, in process_api
    result = await self.call_function(
  File "C:\non-install\ApplioV3.2.0\env\lib\site-packages\gradio\blocks.py", line 1485, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\non-install\ApplioV3.2.0\env\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\non-install\ApplioV3.2.0\env\lib\site-packages\anyio\_backends\_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
  File "C:\non-install\ApplioV3.2.0\env\lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "C:\non-install\ApplioV3.2.0\env\lib\site-packages\gradio\utils.py", line 808, in wrapper
    response = f(*args, **kwargs)
  File "C:\non-install\ApplioV3.2.0\core.py", line 422, in run_download_script
    model_download_pipeline(model_link)
  File "C:\non-install\ApplioV3.2.0\rvc\lib\tools\model_download.py", line 323, in model_download_pipeline
    file_name = item.split("_nprobe_1_")[1].split("_v1")[0]
IndexError: list index out of range
```

**Expected Behavior**
No error and the voice works...

**Desktop Details:**
- Operating System: Windows 11 on unraid VM

**Comment by Maitresinh** [comment]
thank you. Could you be more explicit please ?
You mean that the index file have to have the same name as the pth file ?
By drag and drop, you mean adding a new index ? Where can i get it ?

**Comment by blaise-tk** [comment]
download the zip, extract it and drag an drop it in the download setion
