### ISSUE TITLE
[BUG] Applio 3.1.0 Stable MacOS

### ISSUE THREAD

**Issue by BibouOnAir** [IAHispano/Applio#477]
Hi,

I installed Appli version 3.1.0 on mac OS X by following the guide on Applio.org

Here are the errors I get at startup:
```

No supported Nvidia GPU found
Using FP32 config instead of FP16 due to GPU compatibility (None)
/Users/bibou/Downloads/Applio-3.1.0/.venv/lib/python3.9/site-packages/threadpoolctl.py:1214: RuntimeWarning: 
Found Intel OpenMP ('libiomp') and LLVM OpenMP ('libomp') loaded at
the same time. Both libraries are known to be incompatible and this
can cause random crashes or deadlocks on Linux when loaded in the
same Python program.
Using threadpoolctl may cause crashes or deadlocks. For more
information and possible workarounds, please see
    https://github.com/joblib/threadpoolctl/blob/master/multiple_openmp.md

  warnings.warn(msg, RuntimeWarning)

Downloading https://huggingface.co/IAHispano/Applio/resolve/main/Resources/hubert_base.pt to hubert_base.pt...
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 1346, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1040, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 980, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1454, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/bibou/Downloads/Applio-3.1.0/rvc/lib/tools/prerequisites_download.py", line 85, in <module>
    download_files(models)
  File "/Users/bibou/Downloads/Applio-3.1.0/rvc/lib/tools/prerequisites_download.py", line 81, in download_files
    wget.download(url, out=destination_path)
  File "/Users/bibou/Downloads/Applio-3.1.0/.venv/lib/python3.9/site-packages/wget.py", line 526, in download
    (tmpfile, headers) = ulib.urlretrieve(binurl, tmpfile, callback)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 239, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 1389, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 1349, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)>
Error: Unable to connect to Rich Presence. Could not find Discord installed and running on this machine.
Theme Loaded: Applio
Running on local URL:  http://127.0.0.1:6969

To create a public link, set `share=True` in `launch()`.
```

The Applio interface launches in Google Chrome, this is what I get when I try to generate a voice

<img width="1970" alt="Capture d’écran 2024-06-23 à 18 37 47" src="https://github.com/IAHispano/Applio/assets/173623361/135c2c45-fa63-4b6b-ad5c-bee19155e4e2">

```
/Users/bibou/Downloads/Applio-3.1.0/.venv/lib/python3.9/site-packages/threadpoolctl.py:1214: RuntimeWarning: 
Found Intel OpenMP ('libiomp') and LLVM OpenMP ('libomp') loaded at
the same time. Both libraries are known to be incompatible and this
can cause random crashes or deadlocks on Linux when loaded in the
same Python program.
Using threadpoolctl may cause crashes or deadlocks. For more
information and possible workarounds, please see
    https://github.com/joblib/threadpoolctl/blob/master/multiple_openmp.md

  warnings.warn(msg, RuntimeWarning)
Traceback (most recent call last):
  File "/Users/bibou/Downloads/Applio-3.1.0/rvc/infer/infer.py", line 9, in <module>
    from pipeline import VC
  File "/Users/bibou/Downloads/Applio-3.1.0/rvc/infer/pipeline.py", line 17, in <module>
    from rvc.lib.FCPEF0Predictor import FCPEF0Predictor
  File "/Users/bibou/Downloads/Applio-3.1.0/rvc/lib/FCPEF0Predictor.py", line 18, in <module>
    from local_attention import LocalAttention
ModuleNotFoundError: No module named 'local_attention'
Traceback (most recent call last):
  File "/Users/bibou/Downloads/Applio-3.1.0/.venv/lib/python3.9/site-packages/gradio/queueing.py", line 495, in call_prediction
    output = await route_utils.call_process_api(
  File "/Users/bibou/Downloads/Applio-3.1.0/.venv/lib/python3.9/site-packages/gradio/route_utils.py", line 230, in call_process_api
    output = await app.get_blocks().process_api(
  File "/Users/bibou/Downloads/Applio-3.1.0/.venv/lib/python3.9/site-packages/gradio/blocks.py", line 1599, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/Users/bibou/Downloads/Applio-3.1.0/.venv/lib/python3.9/site-packages/gradio/blocks.py", line 1453, in postprocess_data
    outputs_cached = processing_utils.move_files_to_cache(
  File "/Users/bibou/Downloads/Applio-3.1.0/.venv/lib/python3.9/site-packages/gradio/processing_utils.py", line 267, in move_files_to_cache
    return client_utils.traverse(data, _move_to_cache, client_utils.is_file_obj)
  File "/Users/bibou/Downloads/Applio-3.1.0/.venv/lib/python3.9/site-packages/gradio_client/utils.py", line 981, in traverse
    return func(json_obj)
  File "/Users/bibou/Downloads/Applio-3.1.0/.venv/lib/python3.9/site-packages/gradio/processing_utils.py", line 259, in _move_to_cache
    temp_file_path = move_resource_to_block_cache(payload.path, block)
  File "/Users/bibou/Downloads/Applio-3.1.0/.venv/lib/python3.9/site-packages/gradio/processing_utils.py", line 236, in move_resource_to_block_cache
    return block.move_resource_to_block_cache(url_or_file_path)
  File "/Users/bibou/Downloads/Applio-3.1.0/.venv/lib/python3.9/site-packages/gradio/blocks.py", line 257, in move_resource_to_block_cache
    temp_file_path = processing_utils.save_file_to_cache(
  File "/Users/bibou/Downloads/Applio-3.1.0/.venv/lib/python3.9/site-packages/gradio/processing_utils.py", line 170, in save_file_to_cache
    temp_dir = hash_file(file_path)
  File "/Users/bibou/Downloads/Applio-3.1.0/.venv/lib/python3.9/site-packages/gradio/processing_utils.py", line 102, in hash_file
    with open(file_path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/bibou/Downloads/Applio-3.1.0/assets/audios/cest_le_morning_de_difool_output.wav'
```

On MacBook Pro Apple M1 Max
MacOS 14.4.1
Google Chrome Navigator

**Comment by Anthonyxd22** [comment]
Some dependencies are not working for now and it is a no module error

**Comment by BibouOnAir** [comment]
Is there no way to repair it?

For example, I installed all the modules, but I still got an error: "ModuleNotFoundError: No module named 'local_attention'"

However I installed "pip install local_attention"

Do you know where the problem could be?

thanks a lot for your help



```
/Users/bibou/Downloads/Applio-3.1.0/.venv/lib/python3.9/site-packages/threadpoolctl.py:1214: RuntimeWarning: 
Found Intel OpenMP ('libiomp') and LLVM OpenMP ('libomp') loaded at
the same time. Both libraries are known to be incompatible and this
can cause random crashes or deadlocks on Linux when loaded in the
same Python program.
Using threadpoolctl may cause crashes or deadlocks. For more
information and possible workarounds, please see
    https://github.com/joblib/threadpoolctl/blob/master/multiple_openmp.md

  warnings.warn(msg, RuntimeWarning)
Traceback (most recent call last):
  File "/Users/bibou/Downloads/Applio-3.1.0/rvc/infer/infer.py", line 9, in <module>
    from pipeline import VC
  File "/Users/bibou/Downloads/Applio-3.1.0/rvc/infer/pipeline.py", line 17, in <module>
    from rvc.lib.FCPEF0Predictor import FCPEF0Predictor
  File "/Users/bibou/Downloads/Applio-3.1.0/rvc/lib/FCPEF0Predictor.py", line 18, in <module>
    from local_attention import LocalAttention
ModuleNotFoundError: No module named 'local_attention'
Traceback (most recent call last):
  File "/Users/bibou/Downloads/Applio-3.1.0/.venv/lib/python3.9/site-packages/gradio/queueing.py", line 495, in call_prediction
    output = await route_utils.call_process_api(
  File "/Users/bibou/Downloads/Applio-3.1.0/.venv/lib/python3.9/site-packages/gradio/route_utils.py", line 230, in call_process_api
    output = await app.get_blocks().process_api(
  File "/Users/bibou/Downloads/Applio-3.1.0/.venv/lib/python3.9/site-packages/gradio/blocks.py", line 1599, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/Users/bibou/Downloads/Applio-3.1.0/.venv/lib/python3.9/site-packages/gradio/blocks.py", line 1453, in postprocess_data
    outputs_cached = processing_utils.move_files_to_cache(
  File "/Users/bibou/Downloads/Applio-3.1.0/.venv/lib/python3.9/site-packages/gradio/processing_utils.py", line 267, in move_files_to_cache
    return client_utils.traverse(data, _move_to_cache, client_utils.is_file_obj)
  File "/Users/bibou/Downloads/Applio-3.1.0/.venv/lib/python3.9/site-packages/gradio_client/utils.py", line 981, in traverse
    return func(json_obj)
  File "/Users/bibou/Downloads/Applio-3.1.0/.venv/lib/python3.9/site-packages/gradio/processing_utils.py", line 259, in _move_to_cache
    temp_file_path = move_resource_to_block_cache(payload.path, block)
  File "/Users/bibou/Downloads/Applio-3.1.0/.venv/lib/python3.9/site-packages/gradio/processing_utils.py", line 236, in move_resource_to_block_cache
    return block.move_resource_to_block_cache(url_or_file_path)
  File "/Users/bibou/Downloads/Applio-3.1.0/.venv/lib/python3.9/site-packages/gradio/blocks.py", line 257, in move_resource_to_block_cache
    temp_file_path = processing_utils.save_file_to_cache(
  File "/Users/bibou/Downloads/Applio-3.1.0/.venv/lib/python3.9/site-packages/gradio/processing_utils.py", line 170, in save_file_to_cache
    temp_dir = hash_file(file_path)
  File "/Users/bibou/Downloads/Applio-3.1.0/.venv/lib/python3.9/site-packages/gradio/processing_utils.py", line 102, in hash_file
    with open(file_path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/bibou/Downloads/Applio-3.1.0/assets/audios/cest_le_output.wav'


```

**Comment by Anthonyxd22** [comment]
https://docs.google.com/document/d/10ZyhkaJGdoa_M7QVUmlNSe94brAYG1BusKS4EHTrtwc/edit

**Comment by Anthonyxd22** [comment]
I already updated it, it should work for you

**Comment by Anthonyxd22** [comment]
https://applio.org/guides/54 updated

**Comment by BibouOnAir** [comment]
Thank you so much,

I followed step by step, I have missing modules even though I use them.

I therefore do them manually,

and it still doesn't work



```
Traceback (most recent call last):
  File "/Users/bibou/Downloads/Applio-3.1.0/app.py", line 10, in <module>
    from tabs.inference.inference import inference_tab
  File "/Users/bibou/Downloads/Applio-3.1.0/tabs/inference/inference.py", line 3, in <module>
    import regex as re
ModuleNotFoundError: No module named 'regex'
```

**Comment by BibouOnAir** [comment]
```
(.venv) bibou@MacBook-Pro-de-Bibou Applio-3.1.0 % gradio manually sh run-applio.sh
Usage: gradio [OPTIONS] DEMO_PATH
Try 'gradio --help' for help.
╭─ Error ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Got unexpected extra arguments (sh run-applio.sh)    
```

**Comment by BibouOnAir** [comment]
```
No supported Nvidia GPU found
Using FP32 config instead of FP16 due to GPU compatibility (None)
/Users/bibou/Downloads/Applio-3.1.0/.venv/lib/python3.10/site-packages/threadpoolctl.py:1214: RuntimeWarning: 
Found Intel OpenMP ('libiomp') and LLVM OpenMP ('libomp') loaded at
the same time. Both libraries are known to be incompatible and this
can cause random crashes or deadlocks on Linux when loaded in the
same Python program.
Using threadpoolctl may cause crashes or deadlocks. For more
information and possible workarounds, please see
    https://github.com/joblib/threadpoolctl/blob/master/multiple_openmp.md

  warnings.warn(msg, RuntimeWarning)

Downloading https://huggingface.co/IAHispano/Applio/resolve/main/Resources/hubert_base.pt to hubert_base.pt...
100% [......................................................................] 189507909 / 189507909
Downloading https://huggingface.co/IAHispano/Applio/resolve/main/Resources/rmvpe.pt to rmvpe.pt...
100% [......................................................................] 181184272 / 181184272
Downloading https://huggingface.co/IAHispano/Applio/resolve/main/Resources/fcpe.pt to fcpe.pt...
100% [........................................................................] 69005189 / 69005189
Downloading https://huggingface.co/IAHispano/Applio/resolve/main/Resources/pretrained_v2/D32k.pth to rvc/pretraineds/pretrained_v2/D32k.pth...
100% [......................................................................] 142875703 / 142875703
Downloading https://huggingface.co/IAHispano/Applio/resolve/main/Resources/pretrained_v2/D40k.pth to rvc/pretraineds/pretrained_v2/D40k.pth...
100% [......................................................................] 142875703 / 142875703
Downloading https://huggingface.co/IAHispano/Applio/resolve/main/Resources/pretrained_v2/D48k.pth to rvc/pretraineds/pretrained_v2/D48k.pth...
100% [......................................................................] 142875703 / 142875703
Downloading https://huggingface.co/IAHispano/Applio/resolve/main/Resources/pretrained_v2/G32k.pth to rvc/pretraineds/pretrained_v2/G32k.pth...
100% [........................................................................] 73811639 / 73811639
Downloading https://huggingface.co/IAHispano/Applio/resolve/main/Resources/pretrained_v2/G40k.pth to rvc/pretraineds/pretrained_v2/G40k.pth...
100% [........................................................................] 72959671 / 72959671
Downloading https://huggingface.co/IAHispano/Applio/resolve/main/Resources/pretrained_v2/G48k.pth to rvc/pretraineds/pretrained_v2/G48k.pth...
100% [........................................................................] 75318967 / 75318967
Downloading https://huggingface.co/IAHispano/Applio/resolve/main/Resources/pretrained_v2/f0D32k.pth to rvc/pretraineds/pretrained_v2/f0D32k.pth...
100% [......................................................................] 142875703 / 142875703
Downloading https://huggingface.co/IAHispano/Applio/resolve/main/Resources/pretrained_v2/f0D40k.pth to rvc/pretraineds/pretrained_v2/f0D40k.pth...
100% [......................................................................] 142875703 / 142875703
Downloading https://huggingface.co/IAHispano/Applio/resolve/main/Resources/pretrained_v2/f0D48k.pth to rvc/pretraineds/pretrained_v2/f0D48k.pth...
100% [......................................................................] 142875703 / 142875703
Downloading https://huggingface.co/IAHispano/Applio/resolve/main/Resources/pretrained_v2/f0G32k.pth to rvc/pretraineds/pretrained_v2/f0G32k.pth...
100% [........................................................................] 73950049 / 73950049
Downloading https://huggingface.co/IAHispano/Applio/resolve/main/Resources/pretrained_v2/f0G40k.pth to rvc/pretraineds/pretrained_v2/f0G40k.pth...
100% [........................................................................] 73106273 / 73106273
Downloading https://huggingface.co/IAHispano/Applio/resolve/main/Resources/pretrained_v2/f0G48k.pth to rvc/pretraineds/pretrained_v2/f0G48k.pth...
100% [........................................................................] 75465569 / 75465569Error: Unable to connect to Rich Presence. Could not find Discord installed and running on this machine.
Theme Loaded: Applio
Running on local URL:  http://127.0.0.1:6969
IMPORTANT: You are using gradio version 4.17.0, however version 4.29.0 is available, please upgrade.
--------

To create a public link, set `share=True` in `launch()`.
added_IVF848_Flat_nprobe_1_angele400_v1.index saved in /Users/bibou/Downloads/Applio-3.1.0/logs/angele400
angele400.pth saved in /Users/bibou/Downloads/Applio-3.1.0/logs/angele400
/Users/bibou/Downloads/Applio-3.1.0/.venv/lib/python3.10/site-packages/threadpoolctl.py:1214: RuntimeWarning: 
Found Intel OpenMP ('libiomp') and LLVM OpenMP ('libomp') loaded at
the same time. Both libraries are known to be incompatible and this
can cause random crashes or deadlocks on Linux when loaded in the
same Python program.
Using threadpoolctl may cause crashes or deadlocks. For more
information and possible workarounds, please see
    https://github.com/joblib/threadpoolctl/blob/master/multiple_openmp.md

  warnings.warn(msg, RuntimeWarning)
Traceback (most recent call last):
  File "/Users/bibou/Downloads/Applio-3.1.0/rvc/infer/infer.py", line 9, in <module>
    from pipeline import VC
  File "/Users/bibou/Downloads/Applio-3.1.0/rvc/infer/pipeline.py", line 17, in <module>
    from rvc.lib.FCPEF0Predictor import FCPEF0Predictor
  File "/Users/bibou/Downloads/Applio-3.1.0/rvc/lib/FCPEF0Predictor.py", line 18, in <module>
    from local_attention import LocalAttention
ModuleNotFoundError: No module named 'local_attention'
Traceback (most recent call last):
  File "/Users/bibou/Downloads/Applio-3.1.0/.venv/lib/python3.10/site-packages/gradio/queueing.py", line 495, in call_prediction
    output = await route_utils.call_process_api(
  File "/Users/bibou/Downloads/Applio-3.1.0/.venv/lib/python3.10/site-packages/gradio/route_utils.py", line 230, in call_process_api
    output = await app.get_blocks().process_api(
  File "/Users/bibou/Downloads/Applio-3.1.0/.venv/lib/python3.10/site-packages/gradio/blocks.py", line 1599, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/Users/bibou/Downloads/Applio-3.1.0/.venv/lib/python3.10/site-packages/gradio/blocks.py", line 1453, in postprocess_data
    outputs_cached = processing_utils.move_files_to_cache(
  File "/Users/bibou/Downloads/Applio-3.1.0/.venv/lib/python3.10/site-packages/gradio/processing_utils.py", line 267, in move_files_to_cache
    return client_utils.traverse(data, _move_to_cache, client_utils.is_file_obj)
  File "/Users/bibou/Downloads/Applio-3.1.0/.venv/lib/python3.10/site-packages/gradio_client/utils.py", line 981, in traverse
    return func(json_obj)
  File "/Users/bibou/Downloads/Applio-3.1.0/.venv/lib/python3.10/site-packages/gradio/processing_utils.py", line 259, in _move_to_cache
    temp_file_path = move_resource_to_block_cache(payload.path, block)
  File "/Users/bibou/Downloads/Applio-3.1.0/.venv/lib/python3.10/site-packages/gradio/processing_utils.py", line 236, in move_resource_to_block_cache
    return block.move_resource_to_block_cache(url_or_file_path)
  File "/Users/bibou/Downloads/Applio-3.1.0/.venv/lib/python3.10/site-packages/gradio/blocks.py", line 257, in move_resource_to_block_cache
    temp_file_path = processing_utils.save_file_to_cache(
  File "/Users/bibou/Downloads/Applio-3.1.0/.venv/lib/python3.10/site-packages/gradio/processing_utils.py", line 170, in save_file_to_cache
    temp_dir = hash_file(file_path)
  File "/Users/bibou/Downloads/Applio-3.1.0/.venv/lib/python3.10/site-packages/gradio/processing_utils.py", line 102, in hash_file
    with open(file_path, "rb") as f:

```

**Comment by BibouOnAir** [comment]
I installed the "local_attention" module

This is the result now

```
Running on local URL:  http://127.0.0.1:6969

To create a public link, set `share=True` in `launch()`.
IMPORTANT: You are using gradio version 4.17.0, however version 4.29.0 is available, please upgrade.
--------
/Users/bibou/Downloads/Applio-3.1.0/.venv/lib/python3.10/site-packages/gradio/processing_utils.py:347: UserWarning: Trying to convert audio automatically from int32 to 16-bit int format.
  warnings.warn(warning.format(data.dtype))
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/bibou/Downloads/Applio-3.1.0/.venv/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/Users/bibou/Downloads/Applio-3.1.0/.venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
  File "/Users/bibou/Downloads/Applio-3.1.0/.venv/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/bibou/Downloads/Applio-3.1.0/.venv/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/bibou/Downloads/Applio-3.1.0/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/Users/bibou/Downloads/Applio-3.1.0/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/Users/bibou/Downloads/Applio-3.1.0/.venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "/Users/bibou/Downloads/Applio-3.1.0/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/bibou/Downloads/Applio-3.1.0/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/bibou/Downloads/Applio-3.1.0/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/bibou/Downloads/Applio-3.1.0/.venv/lib/python3.10/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/bibou/Downloads/Applio-3.1.0/.venv/lib/python3.10/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/Users/bibou/Downloads/Applio-3.1.0/.venv/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/Users/bibou/Downloads/Applio-3.1.0/.venv/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Users/bibou/Downloads/Applio-3.1.0/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/bibou/Downloads/Applio-3.1.0/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/bibou/Downloads/Applio-3.1.0/.venv/lib/python3.10/site-packages/starlette/routing.py", line 75, in app
    await response(scope, receive, send)
  File "/Users/bibou/Downloads/Applio-3.1.0/.venv/lib/python3.10/site-packages/starlette/responses.py", line 352, in __call__
    await send(
  File "/Users/bibou/Downloads/Applio-3.1.0/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 50, in sender
    await send(message)
  File "/Users/bibou/Downloads/Applio-3.1.0/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 50, in sender
    await send(message)
  File "/Users/bibou/Downloads/Applio-3.1.0/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 161, in _send
    await send(message)
  File "/Users/bibou/Downloads/Applio-3.1.0/.venv/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 534, in send
    raise RuntimeError("Response content shorter than Content-Length")
RuntimeError: Response content shorter than Content-Length
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/bibou/Downloads/Applio-3.1.0/.venv/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/Users/bibou/Downloads/Applio-3.1.0/.venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
  File "/Users/bibou/Downloads/Applio-3.1.0/.venv/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/bibou/Downloads/Applio-3.1.0/.venv/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/bibou/Downloads/Applio-3.1.0/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/Users/bibou/Downloads/Applio-3.1.0/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/Users/bibou/Downloads/Applio-3.1.0/.venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "/Users/bibou/Downloads/Applio-3.1.0/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/bibou/Downloads/Applio-3.1.0/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/bibou/Downloads/Applio-3.1.0/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/bibou/Downloads/Applio-3.1.0/.venv/lib/python3.10/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/bibou/Downloads/Applio-3.1.0/.venv/lib/python3.10/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/Users/bibou/Downloads/Applio-3.1.0/.venv/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/Users/bibou/Downloads/Applio-3.1.0/.venv/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Users/bibou/Downloads/Applio-3.1.0/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/bibou/Downloads/Applio-3.1.0/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/bibou/Downloads/Applio-3.1.0/.venv/lib/python3.10/site-packages/starlette/routing.py", line 75, in app
    await response(scope, receive, send)
  File "/Users/bibou/Downloads/Applio-3.1.0/.venv/lib/python3.10/site-packages/starlette/responses.py", line 352, in __call__
    await send(
  File "/Users/bibou/Downloads/Applio-3.1.0/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 50, in sender
    await send(message)
  File "/Users/bibou/Downloads/Applio-3.1.0/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 50, in sender
    await send(message)
  File "/Users/bibou/Downloads/Applio-3.1.0/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 161, in _send
    await send(message)
  File "/Users/bibou/Downloads/Applio-3.1.0/.venv/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 534, in send
    raise RuntimeError("Response content shorter than Content-Length")
RuntimeError: Response content shorter than Content-Length


```

**Comment by Anthonyxd22** [comment]
What version of Python do you have?

**Comment by BibouOnAir** [comment]
I completely uninstalled Python

And I followed the steps in the new applio V3 mac OS guide

So I have Python 3.11

**Comment by BibouOnAir** [comment]
```
(.venv) bibou@MacBook-Pro-de-Bibou Applio-3.1.0 % python --version
Python 3.9.8
```

**Comment by BibouOnAir** [comment]
Can you install it for me?
I'm making a donation to you.

I really need Applio for my work, I'm willing to pay to have it, you guys seem to be the best

**Comment by Anthonyxd22** [comment]
downloading the most updated version of apple should fix that gh repo clone IAHispano/Applio

**Comment by Anthonyxd22** [comment]
downloading the most updated version of apple should fix that gh repo clone IAHispano/Applio

**Comment by Anthonyxd22** [comment]
> downloading the most updated version of applio should fix that

**Comment by BibouOnAir** [comment]
no :( 

```
Overwritten preprocess and config.json to use FP32.
/Users/bibou/Downloads/Applio-main/.venv/lib/python3.10/site-packages/threadpoolctl.py:1214: RuntimeWarning: 
Found Intel OpenMP ('libiomp') and LLVM OpenMP ('libomp') loaded at
the same time. Both libraries are known to be incompatible and this
can cause random crashes or deadlocks on Linux when loaded in the
same Python program.
Using threadpoolctl may cause crashes or deadlocks. For more
information and possible workarounds, please see
    https://github.com/joblib/threadpoolctl/blob/master/multiple_openmp.md

  warnings.warn(msg, RuntimeWarning)
/Users/bibou/Downloads/Applio-main/.venv/lib/python3.10/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: 'dlopen(/Users/bibou/Downloads/Applio-main/.venv/lib/python3.10/site-packages/torchvision/image.so, 0x0006): Symbol not found: __ZN3c1017RegisterOperatorsD1Ev
  Referenced from: <44F0DED1-707A-3C3A-827B-888BD52487EB> /Users/bibou/Downloads/Applio-main/.venv/lib/python3.10/site-packages/torchvision/image.so
  Expected in:     <A84DFEFF-287E-3B94-A7DB-731FA5F9CBBC> /Users/bibou/Downloads/Applio-main/.venv/lib/python3.10/site-packages/torch/lib/libtorch_cpu.dylib'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
Traceback (most recent call last):
  File "/Users/bibou/Downloads/Applio-main/app.py", line 9, in <module>
    from tabs.inference.inference import inference_tab
  File "/Users/bibou/Downloads/Applio-main/tabs/inference/inference.py", line 7, in <module>
    from core import (
  File "/Users/bibou/Downloads/Applio-main/core.py", line 20, in <module>
    from rvc.infer.infer import VoiceConverter
  File "/Users/bibou/Downloads/Applio-main/rvc/infer/infer.py", line 11, in <module>
    from rvc.lib.utils import load_audio, load_embedding
  File "/Users/bibou/Downloads/Applio-main/rvc/lib/utils.py", line 6, in <module>
    from fairseq import checkpoint_utils
ModuleNotFoundError: No module named 'fairseq'
```

**Comment by Anthonyxd22** [comment]
Write to me on discord to explain better anthonydiazjorges

**Comment by blaisewf** [comment]
fixed
