### ISSUE TITLE
[BUG] Elevenlabs-TTS 1 plugin installed in colab

### ISSUE THREAD

**Issue by mikhail2013ru** [IAHispano/Applio#498]
Elevenlabs-TTS 1 plugin installed in /content/programml/tabs/plugins/installed! Restarting applio to apply the changes.
H2024-07-09 10:07:49.168126: E external/localxla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-07-09 10:07:49.168190: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-07-09 10:07:49.170344: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-07-09 10:07:50.329420: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
New plugin Elevenlabs-TTS found, installing it...
Traceback (most recent call last):
  File "/content/program_ml/app.py", line 16, in <module>
    from tabs.plugins.plugins import plugins_tab
  File "/content/program_ml/tabs/plugins/plugins.py", line 13, in <module>
    plugins_core.check_new_folders()
  File "/content/program_ml/tabs/plugins/plugins_core.py", line 109, in check_new_folders
    subprocess.run(
  File "/usr/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'env/python.exe'

**Comment by blaisewf** [comment]
Seems a bit strange your error, we only select the env/python.exe if it's an WIN environment https://github.com/IAHispano/Applio/blob/main/tabs/plugins/plugins_core.py#L62

**Comment by blaisewf** [comment]
Can you try again? Pushed a fix

**Comment by mikhail2013ru** [comment]
File "C:\ApplioV3.2.1\tabs\plugins\installed\Elevenlabs-TTS\plugin.py", line 168, in run_tts_script
    voice_converter.infer_pipeline(
TypeError: infer_pipeline() missing 2 required positional arguments: 'upscale_audio' and 'f0_file'

error in local version 3.2.1
