### ISSUE TITLE
Using Applio with AMD GPU using HIP SDK and Zluda

### ISSUE THREAD

**Issue by AznamirWoW** [IAHispano/Applio#503]
Applio with Zluda:

1) for every .py file that has 'import torch' add

 import torch
+#start Zluda changes
+torch.backends.cudnn.enabled = False
+torch.backends.cuda.enable_flash_sdp(False)
+torch.backends.cuda.enable_math_sdp(True)
+torch.backends.cuda.enable_mem_efficient_sdp(False)
+#end Zluda changes

not _every_ file has to change, but there are too many imports to manually check which one is actually needed

2) HIP Crash prevention. in rvc/lib/algorithm/attentions.py make the following change in fused_add_tanh_sigmoid_multiply

     t_act = torch.tanh(in_act[:, :n_channels_int, :])
     s_act = torch.sigmoid(in_act[:, n_channels_int:, :])
+    print('!!!') #this avoids HIP crash somehow
     acts = t_act * s_act
     return acts
	 
3) Torch FFT changes

	3.1) rvc/lib/predictors/RMVPE.py
	
+cpu_dev = torch.device("cpu")
+cud_dev = torch.device("cuda")
	
	...
	
+        #start Zluda changes
+        #HIP SDK does have a match for cuFFTs, so using CPU to do that instead
+        ac = audio.to(cpu_dev)
+        wc = self.hann_window[keyshift_key].to(cpu_dev)
         fft = torch.stft(
-            audio,
+            ac,
             n_fft=n_fft_new,
             hop_length=hop_length_new,
             win_length=win_length_new,
-            window=self.hann_window[keyshift_key],
+            window=wc,
             center=center,
             return_complex=True,
         )
+        fft = fft.to(cud_dev)
+        #end Zluda changes

	3.2) rvc/train/mel_processing.py
	
+cpu_dev = torch.device("cpu")
+cud_dev = torch.device("cuda")

...

+    #start Zluda changes
+    #HIP SDK does have a match for cuFFTs, so using CPU to do that instead
+    yc = y.to(cpu_dev)
+    wc = hann_window[wnsize_dtype_device].to(cpu_dev)
     spec = torch.stft(
-        y,
+        yc,
         n_fft,
         hop_length=hop_size,
         win_length=win_size,
-        window=hann_window[wnsize_dtype_device],
+        window=wc,
         center=center,
         pad_mode="reflect",
         normalized=False,
         onesided=True,
         return_complex=True,
     )
-
+    spec = spec.to(cud_dev)
+    #end Zluda changes

4) modify run-install.bat to fetch cu118 libraries

	pip install torch==2.1.1 torchvision==0.16.1 torchaudio==2.1.1 --index-url https://download.pytorch.org/whl/cu118

5) Install pre-requisites:
	a) HIP SDK 6.1.2 https://www.amd.com/en/developer/resources/rocm-hub/hip-sdk.html
	b) Zluda 3.8 https://github.com/lshqqytiger/ZLUDA/releases/tag/rel.86cdab3b14b556e95eafe370b8e8a1a80e8d093b
	c) if using 6700(XT) or 6600(XT) need to find/compile a custom set of optimized rocm libraries
	
6) unzip Zluda into zluda folder, run patch torch libs

copy zluda\cublas.dll env\Lib\site-packages\torch\lib\cublas64_11.dll /y
copy zluda\cusparse.dll env\Lib\site-packages\torch\lib\cusparse64_11.dll /y
copy zluda\nvrtc.dll env\Lib\site-packages\torch\lib\nvrtc64_112_0.dll /y

7) start Applio using 
	
zluda\zluda.exe -- env\python.exe app.py

**Comment by AznamirWoW** [comment]
never mind, at the moment the training part is unstable and crashes HIP in fused_add_tanh_sigmoid_multiply

**Comment by AznamirWoW** [comment]
updated diff
[Applio_Zluda.patch](https://github.com/user-attachments/files/16230106/Applio_Zluda.patch)

**Comment by 27kaive** [comment]
how do u apply the patch? i get a lot of errors which say "patch does not apply"

**Comment by AznamirWoW** [comment]
> how do u apply the patch? i get a lot of errors which say "patch does not apply"

I've created a proper pull request with the required changes. You can apply them manually to 3.2.1 version if you want.

**Comment by tej1940** [comment]
i am not really good in coding so where i past this thing please ?
copy zluda\cublas.dll env\Lib\site-packages\torch\lib\cublas64_11.dll /y
copy zluda\cusparse.dll env\Lib\site-packages\torch\lib\cusparse64_11.dll /y
copy zluda\nvrtc.dll env\Lib\site-packages\torch\lib\nvrtc64_112_0.dll /y

**Comment by AznamirWoW** [comment]
Note that 1st time Zluda gets a task to process it may take 10-20 minutes for it to compile a kernel code. During this time there's no visible output. Sit tight and wait until it it done.

**Comment by fcastro97** [comment]
> > how do u apply the patch? i get a lot of errors which say "patch does not apply"
> 
> I've created a proper pull request with the required changes. You can apply them manually to 3.2.1 version if you want.

Is the version you made working?

**Comment by AznamirWoW** [comment]
> > > how do u apply the patch? i get a lot of errors which say "patch does not apply"
> > 
> > 
> > I've created a proper pull request with the required changes. You can apply them manually to 3.2.1 version if you want.
> 
> Is the version you made working?

works fine with 3.2.1 and 3.2.2

**Comment by blaisewf** [comment]
I will leave this issue pinned so that users can share their feedback and consider an implementation in the near future.

**Comment by Minksh** [comment]
Doesn't seem to work unfortunately. :(

OSError: [WinError 126] The specified module could not be found. Error loading "D:\Applio\env\lib\site-packages\torch\lib\caffe2_nvrtc.dll" or one of its dependencies.

**Comment by Minksh** [comment]
> i am not really good in coding so where i past this thing please ? copy zluda\cublas.dll env\Lib\site-packages\torch\lib\cublas64_11.dll /y copy zluda\cusparse.dll env\Lib\site-packages\torch\lib\cusparse64_11.dll /y copy zluda\nvrtc.dll env\Lib\site-packages\torch\lib\nvrtc64_112_0.dll /y

You use these commands in cmd ;)

but first you want to use `cd yourappliodirectory`. 

If your applio is on another drive you use `cd /d`
`cd /d d:\Applio`

**Comment by Osony** [comment]
All of this is written for Windows, for Linux is different, but im not testing copying libs and launching
HIP SDK installs with ROCm installation, you need to find instructions for your Linux distro.
Modify run-install.sh, execute run-install.sh
Starting Applio (assuming you inside Applio folder and here is zluda folder) is:
`LD_LIBRARY_PATH="zluda:$LD_LIBRARY_PATH" env\python app.py`
But what library's i need to copy? folder "env\lib\python3.10\site-packages\torch\lib\" exist
I have 1 - "libcublas.so.11", "libcublasLt.so.11"; 3 - "libnvrtc-builtins.so.11.8", "libnvrtc-672ee683.so.11.2" and "libcaffe2_nvrtc.so", i don't have anything related to "cusparse", what i need to do? (Fedora Linux, Python 3.10, completed 3 steps from original post)

**Comment by AznamirWoW** [comment]
> All of this is written for Windows, for Linux is different, but im not testing copying libs and launching HIP SDK installs with ROCm installation, you need to find instructions for your Linux distro. Modify run-install.sh, execute run-install.sh Starting Applio (assuming you inside Applio folder and here is zluda folder) is: `LD_LIBRARY_PATH="zluda:$LD_LIBRARY_PATH" env\python app.py` But what library's i need to copy? folder "env\lib\python3.10\site-packages\torch\lib" exist I have 1 - "libcublas.so.11", "libcublasLt.so.11"; 3 - "libnvrtc-builtins.so.11.8", "libnvrtc-672ee683.so.11.2" and "libcaffe2_nvrtc.so", i don't have anything related to "cusparse", what i need to copy and/or replace? (Fedora Linux 40, Python 3.10, completed 3 steps from original post)

There's no easy way to do that on Linux. Most likely you need to build Zluda, then you need to build PyTorch with Zluda.
https://github.com/pytorch/pytorch?tab=readme-ov-file#from-source

**Comment by Osony** [comment]
> > All of this is written for Windows, for Linux is different, but im not testing copying libs and launching HIP SDK installs with ROCm installation, you need to find instructions for your Linux distro. Modify run-install.sh, execute run-install.sh Starting Applio (assuming you inside Applio folder and here is zluda folder) is: `LD_LIBRARY_PATH="zluda:$LD_LIBRARY_PATH" env\python app.py` But what library's i need to copy? folder "env\lib\python3.10\site-packages\torch\lib" exist I have 1 - "libcublas.so.11", "libcublasLt.so.11"; 3 - "libnvrtc-builtins.so.11.8", "libnvrtc-672ee683.so.11.2" and "libcaffe2_nvrtc.so", i don't have anything related to "cusparse", what i need to copy and/or replace? (Fedora Linux 40, Python 3.10, completed 3 steps from original post)
> 
> There's no easy way to do that on Linux. Most likely you need to build Zluda, then you need to build PyTorch with Zluda. https://github.com/pytorch/pytorch?tab=readme-ov-file#from-source and https://github.com/lshqqytiger/ZLUDA?tab=readme-ov-file#pytorch

What about using not
`pip install torch==2.1.1 torchvision==0.16.1 torchaudio==2.1.1 --index-url https://download.pytorch.org/whl/cu118`
but
`pip install torch==2.3.1 torchvision==0.18.1 torchaudio==2.3.1 --index-url https://download.pytorch.org/whl/rocm6.0`
?
Is there any other Nvidia/CUDA related code aside PyTorch? There is some code to looking for right GPU in file config.py line 28, assuming to PyTorch docs, i need to change "cuda:0" to "cuda", but it's not helping, i got error "RuntimeError: HIP error: invalid device function" and idk how to fix that

**Comment by AznamirWoW** [comment]
> > > All of this is written for Windows, for Linux is different, but im not testing copying libs and launching HIP SDK installs with ROCm installation, you need to find instructions for your Linux distro. Modify run-install.sh, execute run-install.sh Starting Applio (assuming you inside Applio folder and here is zluda folder) is: `LD_LIBRARY_PATH="zluda:$LD_LIBRARY_PATH" env\python app.py` But what library's i need to copy? folder "env\lib\python3.10\site-packages\torch\lib" exist I have 1 - "libcublas.so.11", "libcublasLt.so.11"; 3 - "libnvrtc-builtins.so.11.8", "libnvrtc-672ee683.so.11.2" and "libcaffe2_nvrtc.so", i don't have anything related to "cusparse", what i need to copy and/or replace? (Fedora Linux 40, Python 3.10, completed 3 steps from original post)
> > 
> > 
> > There's no easy way to do that on Linux. Most likely you need to build Zluda, then you need to build PyTorch with Zluda. https://github.com/pytorch/pytorch?tab=readme-ov-file#from-source and https://github.com/lshqqytiger/ZLUDA?tab=readme-ov-file#pytorch
> 
> What about using not `pip install torch==2.1.1 torchvision==0.16.1 torchaudio==2.1.1 --index-url https://download.pytorch.org/whl/cu118` but `pip install torch==2.3.1 torchvision==0.18.1 torchaudio==2.3.1 --index-url https://download.pytorch.org/whl/rocm6.0` ? Is there any other Nvidia/CUDA related code aside PyTorch? There is some code to looking for right GPU in file config.py line 28, assuming to PyTorch docs, i need to change "cuda:0" to "cuda", but it's not helping, i got error "RuntimeError: HIP error: invalid device function" and idk how to fix that

if you're using RX 7900 variety, you dont need Zluda, you can just use ROCM Pytorch.

**Comment by BSIdro** [comment]
Does this work with Windows? or do you absolutely need Linux?

**Comment by AznamirWoW** [comment]
> Does this work with Windows? or do you absolutely need Linux?

It is quite opposite. Making it work with Windows is pretty easy, making it work with Linux is a huge P.I.T.A.

**Comment by BSIdro** [comment]
As much for me I'm a novice, I'm trying to get it to work with my rx 6800, but I don't understand how should I proceed?

**Comment by AznamirWoW** [comment]
> As much for me I'm a novice, I'm trying to get it to work with my rx 6800, but I don't understand how should I proceed?

right now you can make the manual changes using PR as an example

https://github.com/IAHispano/Applio/pull/593/commits/2c18fc86ea4cb9aba1e2f4224dca1c88fb6ca25e

there's a readme file to follow as well

**Comment by BSIdro** [comment]
I don't understand I tried to install all this but I got this error in my cmd when I wanted to train the pth

`Embedding Extraction: 100%|█████████████████████████████████████████████████████████| 795/795 [00:02<00:00, 312.69it/s]
Embedding extraction completed in 3.49 seconds.
Disabling CUDNN for traning with Zluda
Process Process-1:
Traceback (most recent call last):
  File "C:\Applio-2c18fc86ea4cb9aba1e2f4224dca1c88fb6ca25e\Applio-2c18fc86ea4cb9aba1e2f4224dca1c88fb6ca25e\env\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Applio-2c18fc86ea4cb9aba1e2f4224dca1c88fb6ca25e\Applio-2c18fc86ea4cb9aba1e2f4224dca1c88fb6ca25e\env\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Applio-2c18fc86ea4cb9aba1e2f4224dca1c88fb6ca25e\Applio-2c18fc86ea4cb9aba1e2f4224dca1c88fb6ca25e\rvc\train\train.py", line 396, in run
    net_g = DDP(net_g, device_ids=[rank])
  File "C:\Applio-2c18fc86ea4cb9aba1e2f4224dca1c88fb6ca25e\Applio-2c18fc86ea4cb9aba1e2f4224dca1c88fb6ca25e\env\lib\site-packages\torch\nn\parallel\distributed.py", line 797, in __init__
    _sync_module_states(
  File "C:\Applio-2c18fc86ea4cb9aba1e2f4224dca1c88fb6ca25e\Applio-2c18fc86ea4cb9aba1e2f4224dca1c88fb6ca25e\env\lib\site-packages\torch\distributed\utils.py", line 292, in _sync_module_states
    _sync_params_and_buffers(process_group, module_states, broadcast_bucket_size, src)
  File "C:\Applio-2c18fc86ea4cb9aba1e2f4224dca1c88fb6ca25e\Applio-2c18fc86ea4cb9aba1e2f4224dca1c88fb6ca25e\env\lib\site-packages\torch\distributed\utils.py", line 306, in _sync_params_and_buffers
    dist._broadcast_coalesced(
RuntimeError: CUDA error: operation not supported
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

An error occurred extracting the index: need at least one array to concatenate
If you are running this code in a virtual environment, make sure you have enough GPU available to generate the Index file.`

**Comment by AznamirWoW** [comment]
> EDIT 2: It works, but it seems rather slow to me, and my GPU doesn't seem to be using much when I look in the task manager? I would say between 3 to 4 minutes for training each epoch GPU at 2%, CPU at 35%

Ttask manager does not always report correct load. Adrenaline Control Panel may show correct values.
Depending on the size of the training data set, training is 4-5x faster than on CPU.

as for Inference, it is ~10x faster than CPU.

**Comment by BSIdro** [comment]
Good !
Indeed, my 6800 is very functional, it seems long enough to train a model, but I think it's due to my 30 minute dataset, or since it's the first time, I have to let it finish and then for the next workout will be faster ?

4 minutes per epoch currently. is this normal?

**Comment by blaisewf** [comment]
not the best speed but considering your dataset it’s okay

**Comment by AznamirWoW** [comment]
> Good ! Indeed, my 6800 is very functional, it seems long enough to train a model, but I think it's due to my 30 minute dataset, or since it's the first time, I have to let it finish and then for the next workout will be faster ?
> 
> 4 minutes per epoch currently. is this normal?

with 23min in sliced_audios 10 epochs take ~30 minutes on my 6700XT
with 42 min in sliced_audios 10 epochs take just under an hour.

Depending on the quality of data / using custom pretrained you dont need that many epochs anyway. In some cases I had good results with just 20.

**Comment by BSIdro** [comment]
Indeed, I did a test on 30 epochs, the model was good enough!
Thanks a lot for the help! I can now use my AMD GPU to train models :)

**Comment by blaisewf** [comment]
merged
