### ISSUE TITLE
'VoiceConverter' object has no attribute 'convert_audio'[BUG]

### ISSUE THREAD

**Issue by dreamily5272** [IAHispano/Applio#518]
Tried to use ElevenLabs plugin, such error encounters:

Traceback (most recent call last):
  File "h:\ApplioV3.2.1\env\lib\site-packages\gradio\queueing.py", line 532, in process_events
    response = await route_utils.call_process_api(
  File "h:\ApplioV3.2.1\env\lib\site-packages\gradio\route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
  File "h:\ApplioV3.2.1\env\lib\site-packages\gradio\blocks.py", line 1923, in process_api
    result = await self.call_function(
  File "h:\ApplioV3.2.1\env\lib\site-packages\gradio\blocks.py", line 1509, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "h:\ApplioV3.2.1\env\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "h:\ApplioV3.2.1\env\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "h:\ApplioV3.2.1\env\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "h:\ApplioV3.2.1\env\lib\site-packages\gradio\utils.py", line 832, in wrapper
    response = f(*args, **kwargs)
  File "h:\ApplioV3.2.1\tabs\plugins\installed\Elevenlabs-TTS\plugin.py", line 181, in run_tts_script
    voice_converter.convert_audio(
AttributeError: 'VoiceConverter' object has no attribute 'convert_audio'

**Comment by AznamirWoW** [comment]
@dreamily5272 Elevenlabs-TTS plugin is compatible with current git clone, not compatible with 3.2.1 version.

**Comment by blaisewf** [comment]
duplicated
