### ISSUE TITLE
[Bug] Python Library Error on Linux

### ISSUE THREAD

**Issue by jezSonic123** [IAHispano/Applio#522]
**Bug Description**
Applio seems to struggle to download some Python libraries, they are either too old, or incompatible

**Steps to Reproduce**
1. Download Ubuntu 22.04.4 LTS (Should work fine in a VM)
2. Download Applio 3.0.7 (From what I know, this is the last version that includes bash scripts for Linux/MacOS)
3. Start instalation process with run-install.sh (It should have some issues with the Libraries)
4. I'm not sure if the program is already running, cause it has shutdown for me, but when I try to install it again, to install that error it just starts from the installation script. But You should now start run-applio.sh if it isn't running already.
5. Input some audio for in the text box, select a voice model, and it should error.

**Expected Behavior**
Applio should do a cover like it does on Windows

**Assets**
"Traceback (most recent call last):
  File "/AI/Applio-3.0.7/rvc/infer/infer.py", line 6, in <module>
    from vc_infer_pipeline import VC
  File "/AI/Applio-3.0.7/rvc/infer/vc_infer_pipeline.py", line 17, in <module>
    from rvc.lib.FCPEF0Predictor import FCPEF0Predictor
  File "/AI/Applio-3.0.7/rvc/lib/FCPEF0Predictor.py", line 8, in <module>
    from torchaudio.transforms import Resample
  File "/AI/Applio-3.0.7/.venv/lib/python3.10/site-packages/torchaudio/__init__.py", line 2, in <module>
    from . import _extension  # noqa  # usort: skip
  File "/AI/Applio-3.0.7/.venv/lib/python3.10/site-packages/torchaudio/_extension/__init__.py", line 38, in <module>
    _load_lib("libtorchaudio")
  File "/AI/Applio-3.0.7/.venv/lib/python3.10/site-packages/torchaudio/_extension/utils.py", line 60, in _load_lib
    torch.ops.load_library(path)
  File "/AI/Applio-3.0.7/.venv/lib/python3.10/site-packages/torch/_ops.py", line 852, in load_library
    ctypes.CDLL(path)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /AI/Applio-3.0.7/.venv/lib/python3.10/site-packages/torchaudio/lib/libtorchaudio.so: undefined symbol: _ZNK3c105Error4whatEv
Traceback (most recent call last):
  File "/AI/Applio-3.0.7/.venv/lib/python3.10/site-packages/gradio/queueing.py", line 495, in call_prediction
    output = await route_utils.call_process_api(
  File "/AI/Applio-3.0.7/.venv/lib/python3.10/site-packages/gradio/route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "/AI/Applio-3.0.7/.venv/lib/python3.10/site-packages/gradio/blocks.py", line 1570, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/AI/Applio-3.0.7/.venv/lib/python3.10/site-packages/gradio/blocks.py", line 1456, in postprocess_data
    outputs_cached = processing_utils.move_files_to_cache(
  File "/AI/Applio-3.0.7/.venv/lib/python3.10/site-packages/gradio/processing_utils.py", line 265, in move_files_to_cache
    return client_utils.traverse(data, _move_to_cache, client_utils.is_file_obj)
  File "/AI/Applio-3.0.7/.venv/lib/python3.10/site-packages/gradio_client/utils.py", line 919, in traverse
    return func(json_obj)
  File "/AI/Applio-3.0.7/.venv/lib/python3.10/site-packages/gradio/processing_utils.py", line 257, in _move_to_cache
    temp_file_path = move_resource_to_block_cache(payload.path, block)
  File "/AI/Applio-3.0.7/.venv/lib/python3.10/site-packages/gradio/processing_utils.py", line 234, in move_resource_to_block_cache
    return block.move_resource_to_block_cache(url_or_file_path)
  File "/AI/Applio-3.0.7/.venv/lib/python3.10/site-packages/gradio/blocks.py", line 258, in move_resource_to_block_cache
    temp_file_path = processing_utils.save_file_to_cache(
  File "/AI/Applio-3.0.7/.venv/lib/python3.10/site-packages/gradio/processing_utils.py", line 170, in save_file_to_cache
    temp_dir = hash_file(file_path)
  File "/AI/Applio-3.0.7/.venv/lib/python3.10/site-packages/gradio/processing_utils.py", line 102, in hash_file
    with open(file_path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/AI/Applio-3.0.7/assets/audios/Marvels_Guardians_of_the_Galaxy_Pause_Menu_Music_output.wav'"

**Desktop Details:**
- Operating System: Ubuntu 22.04.4 LTS

**Additional Context**
My system also seems to have issues with audio related Python libraries. I would be happy if someone with more knowledge could shed a light on this, why this happens, and can it be fixed. I don't thing it's relevant for this, but I use Pipewire with Pulseaudio compatilibity. Maybe that makes a difference? I also modified Applio path in the log, cause I didn't wanted to show the entire path

**Comment by blaisewf** [comment]
the compiled versions are only for windows, for linux do a git clone of the repo

**Comment by jezSonic123** [comment]
> the compiled versions are only for windows, for linux do a git clone of the repo

Jesus, yeah now it works. Thank You so much. I have spent way too many nights on figuring out why it doesn't work xd
I hope this post helps anyother dummy that does this like I did :p

**Comment by blaisewf** [comment]
xd no problem
