### ISSUE TITLE
[BUG] __init__() got an unexpected keyword argument 'sample_rate' (hybrid[rmvpe+fcpe])

### ISSUE THREAD

**Issue by ZeroCool22** [IAHispano/Applio#543]
This happen when try to use **hybrid[rmvpe+fcpe]**

```
An error occurred connecting to Discord: Could not find Discord installed and running on this machine.
Theme Loaded: Applio
Running on local URL:  http://127.0.0.1:6969

To create a public link, set `share=True` in `launch()`.
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\ZeroCool22\Desktop\Applio-3.2.2\env\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 398, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\ZeroCool22\Desktop\Applio-3.2.2\env\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\ZeroCool22\Desktop\Applio-3.2.2\env\lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\ZeroCool22\Desktop\Applio-3.2.2\env\lib\site-packages\starlette\applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\ZeroCool22\Desktop\Applio-3.2.2\env\lib\site-packages\starlette\middleware\errors.py", line 186, in __call__
    raise exc
  File "C:\Users\ZeroCool22\Desktop\Applio-3.2.2\env\lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\ZeroCool22\Desktop\Applio-3.2.2\env\lib\site-packages\gradio\route_utils.py", line 714, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\ZeroCool22\Desktop\Applio-3.2.2\env\lib\site-packages\starlette\middleware\exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\ZeroCool22\Desktop\Applio-3.2.2\env\lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "C:\Users\ZeroCool22\Desktop\Applio-3.2.2\env\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\ZeroCool22\Desktop\Applio-3.2.2\env\lib\site-packages\starlette\routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\ZeroCool22\Desktop\Applio-3.2.2\env\lib\site-packages\starlette\routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "C:\Users\ZeroCool22\Desktop\Applio-3.2.2\env\lib\site-packages\starlette\routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "C:\Users\ZeroCool22\Desktop\Applio-3.2.2\env\lib\site-packages\starlette\routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\ZeroCool22\Desktop\Applio-3.2.2\env\lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "C:\Users\ZeroCool22\Desktop\Applio-3.2.2\env\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\ZeroCool22\Desktop\Applio-3.2.2\env\lib\site-packages\starlette\routing.py", line 75, in app
    await response(scope, receive, send)
  File "C:\Users\ZeroCool22\Desktop\Applio-3.2.2\env\lib\site-packages\starlette\responses.py", line 352, in __call__
    await send(
  File "C:\Users\ZeroCool22\Desktop\Applio-3.2.2\env\lib\site-packages\starlette\_exception_handler.py", line 50, in sender
    await send(message)
  File "C:\Users\ZeroCool22\Desktop\Applio-3.2.2\env\lib\site-packages\starlette\_exception_handler.py", line 50, in sender
    await send(message)
  File "C:\Users\ZeroCool22\Desktop\Applio-3.2.2\env\lib\site-packages\starlette\middleware\errors.py", line 161, in _send
    await send(message)
  File "C:\Users\ZeroCool22\Desktop\Applio-3.2.2\env\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 502, in send
    output = self.conn.send(event=h11.EndOfMessage())
  File "C:\Users\ZeroCool22\Desktop\Applio-3.2.2\env\lib\site-packages\h11\_connection.py", line 512, in send
    data_list = self.send_with_data_passthrough(event)
  File "C:\Users\ZeroCool22\Desktop\Applio-3.2.2\env\lib\site-packages\h11\_connection.py", line 545, in send_with_data_passthrough
    writer(event, data_list.append)
  File "C:\Users\ZeroCool22\Desktop\Applio-3.2.2\env\lib\site-packages\h11\_writers.py", line 67, in __call__
    self.send_eom(event.headers, write)
  File "C:\Users\ZeroCool22\Desktop\Applio-3.2.2\env\lib\site-packages\h11\_writers.py", line 96, in send_eom
    raise LocalProtocolError("Too little data for declared Content-Length")
h11._util.LocalProtocolError: Too little data for declared Content-Length
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\ZeroCool22\Desktop\Applio-3.2.2\env\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 398, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\ZeroCool22\Desktop\Applio-3.2.2\env\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\ZeroCool22\Desktop\Applio-3.2.2\env\lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\ZeroCool22\Desktop\Applio-3.2.2\env\lib\site-packages\starlette\applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\ZeroCool22\Desktop\Applio-3.2.2\env\lib\site-packages\starlette\middleware\errors.py", line 186, in __call__
    raise exc
  File "C:\Users\ZeroCool22\Desktop\Applio-3.2.2\env\lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\ZeroCool22\Desktop\Applio-3.2.2\env\lib\site-packages\gradio\route_utils.py", line 714, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\ZeroCool22\Desktop\Applio-3.2.2\env\lib\site-packages\starlette\middleware\exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\ZeroCool22\Desktop\Applio-3.2.2\env\lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "C:\Users\ZeroCool22\Desktop\Applio-3.2.2\env\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\ZeroCool22\Desktop\Applio-3.2.2\env\lib\site-packages\starlette\routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\ZeroCool22\Desktop\Applio-3.2.2\env\lib\site-packages\starlette\routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "C:\Users\ZeroCool22\Desktop\Applio-3.2.2\env\lib\site-packages\starlette\routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "C:\Users\ZeroCool22\Desktop\Applio-3.2.2\env\lib\site-packages\starlette\routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\ZeroCool22\Desktop\Applio-3.2.2\env\lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "C:\Users\ZeroCool22\Desktop\Applio-3.2.2\env\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\ZeroCool22\Desktop\Applio-3.2.2\env\lib\site-packages\starlette\routing.py", line 75, in app
    await response(scope, receive, send)
  File "C:\Users\ZeroCool22\Desktop\Applio-3.2.2\env\lib\site-packages\starlette\responses.py", line 352, in __call__
    await send(
  File "C:\Users\ZeroCool22\Desktop\Applio-3.2.2\env\lib\site-packages\starlette\_exception_handler.py", line 50, in sender
    await send(message)
  File "C:\Users\ZeroCool22\Desktop\Applio-3.2.2\env\lib\site-packages\starlette\_exception_handler.py", line 50, in sender
    await send(message)
  File "C:\Users\ZeroCool22\Desktop\Applio-3.2.2\env\lib\site-packages\starlette\middleware\errors.py", line 161, in _send
    await send(message)
  File "C:\Users\ZeroCool22\Desktop\Applio-3.2.2\env\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 502, in send
    output = self.conn.send(event=h11.EndOfMessage())
  File "C:\Users\ZeroCool22\Desktop\Applio-3.2.2\env\lib\site-packages\h11\_connection.py", line 512, in send
    data_list = self.send_with_data_passthrough(event)
  File "C:\Users\ZeroCool22\Desktop\Applio-3.2.2\env\lib\site-packages\h11\_connection.py", line 545, in send_with_data_passthrough
    writer(event, data_list.append)
  File "C:\Users\ZeroCool22\Desktop\Applio-3.2.2\env\lib\site-packages\h11\_writers.py", line 67, in __call__
    self.send_eom(event.headers, write)
  File "C:\Users\ZeroCool22\Desktop\Applio-3.2.2\env\lib\site-packages\h11\_writers.py", line 96, in send_eom
    raise LocalProtocolError("Too little data for declared Content-Length")
h11._util.LocalProtocolError: Too little data for declared Content-Length
2024-08-05 01:52:37 | INFO | faiss.loader | Loading faiss with AVX2 support.
2024-08-05 01:52:37 | INFO | faiss.loader | Could not load library with AVX2 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")
2024-08-05 01:52:37 | INFO | faiss.loader | Loading faiss.
2024-08-05 01:52:37 | INFO | faiss.loader | Successfully loaded faiss.
Converting audio 'assets\audios\2024-08-05_01-33-00.wav'...
Calculating f0 pitch estimations for methods ['rmvpe', 'fcpe']
An error occurred during audio conversion: __init__() got an unexpected keyword argument 'sample_rate'
Traceback (most recent call last):
  File "C:\Users\ZeroCool22\Desktop\Applio-3.2.2\rvc\infer\infer.py", line 256, in convert_audio
    audio_opt = self.vc.pipeline(
  File "C:\Users\ZeroCool22\Desktop\Applio-3.2.2\rvc\infer\pipeline.py", line 585, in pipeline
    pitch, pitchf = self.get_f0(
  File "C:\Users\ZeroCool22\Desktop\Applio-3.2.2\rvc\infer\pipeline.py", line 351, in get_f0
    f0 = self.get_f0_hybrid(
  File "C:\Users\ZeroCool22\Desktop\Applio-3.2.2\rvc\infer\pipeline.py", line 274, in get_f0_hybrid
    self.model_fcpe = FCPEF0Predictor(
TypeError: __init__() got an unexpected keyword argument 'sample_rate'
```

**Expected Behavior**
Convert without this problem.

**Assets**
Include screenshots or videos if they can illustrate the issue.

**Desktop Details:**
- Operating System: [e.g., Windows 10]
- Browser: [Edge, FireFox]

**Additional Context**
```
(C:\Users\ZeroCool22\Miniconda3) C:\Users\ZeroCool22\Desktop\Applio-3.2.2\env\Scripts>pip list
Package                   Version
------------------------- ------------
absl-py                   2.1.0
aiofiles                  23.2.1
aiohappyeyeballs          2.3.4
aiohttp                   3.10.1
aiosignal                 1.3.1
altair                    5.3.0
annotated-types           0.7.0
antlr4-python3-runtime    4.8
anyio                     4.4.0
async-timeout             4.0.3
attrs                     24.1.0
audio_upscaler            0.1.4
audioread                 3.0.1
Babel                     2.15.0
beautifulsoup4            4.12.3
bibtexparser              2.0.0b7
bitarray                  2.9.2
blinker                   1.8.2
certifi                   2023.7.22
cffi                      1.16.0
chardet                   5.2.0
charset-normalizer        3.3.2
click                     8.1.7
clldutils                 3.22.2
colorama                  0.4.6
colorlog                  6.8.2
contourpy                 1.2.1
csvw                      3.3.0
cycler                    0.12.1
Cython                    3.0.10
decorator                 5.1.1
dlinfo                    1.2.1
edge-tts                  6.1.9
einops                    0.8.0
exceptiongroup            1.2.2
fairseq                   0.12.2
faiss-cpu                 1.7.3
fastapi                   0.112.0
ffmpeg-python             0.2.0
ffmpy                     0.3.1
filelock                  3.15.4
Flask                     3.0.3
fonttools                 4.53.1
frozenlist                1.4.1
fsspec                    2024.6.1
ftfy                      6.2.0
future                    1.0.0
gradio                    4.36.0
gradio_client             1.0.1
grpcio                    1.65.4
h11                       0.14.0
httpcore                  1.0.5
httpx                     0.27.0
huggingface-hub           0.24.5
hydra-core                1.0.7
idna                      3.7
importlib_metadata        8.2.0
importlib_resources       6.4.0
isodate                   0.6.1
itsdangerous              2.2.0
Jinja2                    3.1.4
joblib                    1.4.2
jsonschema                4.23.0
jsonschema-specifications 2023.12.1
kiwisolver                1.4.5
language-tags             1.2.0
libf0                     1.0.2
librosa                   0.9.2
llvmlite                  0.40.1
local-attention           1.9.14
lxml                      5.2.2
Markdown                  3.6
markdown-it-py            3.0.0
MarkupSafe                2.1.5
matplotlib                3.7.2
mdurl                     0.1.2
mpmath                    1.3.0
multidict                 6.0.5
networkx                  3.2.1
noisereduce               3.0.2
numba                     0.57.0
numpy                     1.23.5
omegaconf                 2.0.6
orjson                    3.10.6
packaging                 24.1
pandas                    2.2.2
phonemizer                3.3.0
pillow                    10.4.0
pip                       24.0
platformdirs              4.2.2
pooch                     1.8.2
portalocker               2.10.1
praat-parselmouth         0.4.4
progressbar               2.5
protobuf                  4.25.4
pycparser                 2.22
pydantic                  2.8.2
pydantic_core             2.20.1
pydub                     0.25.1
Pygments                  2.18.0
pylatexenc                2.10
pyparsing                 3.0.9
pypresence                4.3.0
python-dateutil           2.9.0.post0
python-multipart          0.0.9
pytz                      2024.1
pywin32                   306
pyworld                   0.3.4
PyYAML                    6.0.1
rdflib                    7.0.0
referencing               0.35.1
regex                     2024.7.24
requests                  2.32.0
resampy                   0.4.3
rfc3986                   1.5.0
rich                      13.7.1
rpds-py                   0.19.1
ruff                      0.5.6
sacrebleu                 2.4.2
safetensors               0.4.3
scikit-learn              1.5.1
scipy                     1.11.1
segments                  2.2.1
semantic-version          2.10.0
setuptools                72.1.0
shellingham               1.5.4
six                       1.16.0
sniffio                   1.3.1
soundfile                 0.12.1
soupsieve                 2.5
starlette                 0.37.2
sympy                     1.13.1
tabulate                  0.9.0
tensorboard               2.17.0
tensorboard-data-server   0.7.2
tensorboardX              2.6.2.2
threadpoolctl             3.5.0
timm                      1.0.8
tokenizers                0.19.1
tomlkit                   0.12.0
toolz                     0.12.1
torch                     2.1.1+cu121
torchaudio                2.1.1+cu121
torchcrepe                0.0.23
torchfcpe                 0.0.4
torchlibrosa              0.1.0
torchvision               0.16.1+cu121
tqdm                      4.66.5
transformers              4.43.3
typer                     0.12.3
typing_extensions         4.12.2
tzdata                    2024.1
Unidecode                 1.3.8
uritemplate               4.1.1
urllib3                   2.2.2
uvicorn                   0.30.5
wcwidth                   0.2.13
websockets                11.0.3
Werkzeug                  3.0.3
wget                      3.2
wheel                     0.43.0
yarl                      1.9.4
zipp                      3.19.2

(C:\Users\ZeroCool22\Miniconda3) C:\Users\ZeroCool22\Desktop\Applio-3.2.2\env\Scripts>
```

**Comment by ZeroCool22** [comment]
Also, i'm running the 3.2.2 version, but when i check for the updates inside the APP, it told me i'm on the 3.2.1... 🤨 

![Screenshot_3](https://github.com/user-attachments/assets/ed9712e8-f96a-4996-a731-0e62bc498448)
![Screenshot_2](https://github.com/user-attachments/assets/67a8a8cb-688e-40a8-8c89-302a628409a1)
![Screenshot_1](https://github.com/user-attachments/assets/46900a00-a51d-45a1-871f-5190d6291853)

**Comment by blaisewf** [comment]
will be fixed in the next update

**Comment by ZeroCool22** [comment]
> will be fixed in the next update

Thx!
