### ISSUE TITLE
got an unexpected keyword argument 'sample_rate'

### ISSUE THREAD

**Issue by Eydahn8** [IAHispano/Applio#547]
I got this when i try to convert an audio file using hybrid[rmvpe+fcpe] and i got a slowed and muffled voice audio, what can it be? 

Converting audio 'assets\audios\BeYou.wav'...
Calculating f0 pitch estimations for methods ['rmvpe', 'fcpe']
An error occurred during audio conversion: __init__() got an unexpected keyword argument 'sample_rate'
Traceback (most recent call last):
  File "C:\Users\Rushi\Desktop\Ai\Applio-3.2.2\rvc\infer\infer.py", line 256, in convert_audio
    audio_opt = self.vc.pipeline(
  File "C:\Users\Rushi\Desktop\Ai\Applio-3.2.2\rvc\infer\pipeline.py", line 585, in pipeline
    pitch, pitchf = self.get_f0(
  File "C:\Users\Rushi\Desktop\Ai\Applio-3.2.2\rvc\infer\pipeline.py", line 351, in get_f0
    f0 = self.get_f0_hybrid(
  File "C:\Users\Rushi\Desktop\Ai\Applio-3.2.2\rvc\infer\pipeline.py", line 274, in get_f0_hybrid
    self.model_fcpe = FCPEF0Predictor(
TypeError: __init__() got an unexpected keyword argument 'sample_rate'

**Comment by blaisewf** [comment]
duplicated, fixed in the next update
