### ISSUE TITLE
[BUG] Bug generates index end of training

### ISSUE THREAD

**Issue by BibouOnAir** [IAHispano/Applio#560]
when the training ends.
It does not generate the index.
Here is the error code.
When I click on Generate an index it does not work
How can I do it?
Thank you

```
JUL | epoch=266 | step=11704 | time=05:21:14 | training_speed=0:00:24 | lowest_value=21.518 (epoch 167 and step 7305) | Number of epochs remaining for overtraining: 1           
Stopping training due to possible overtraining. Lowest generator loss: 21.518049240112305 at epoch 167, step 7305                                                                
Process Process-2:                                                                                                                                                               
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/notebooks/Applio/rvc/train/train.py", line 417, in run
    train_and_evaluate(
  File "/notebooks/Applio/rvc/train/train.py", line 638, in train_and_evaluate
    scaler.scale(loss_disc).backward()
  File "/usr/local/lib/python3.10/site-packages/torch/_tensor.py", line 492, in backward
    torch.autograd.backward(
  File "/usr/local/lib/python3.10/site-packages/torch/autograd/__init__.py", line 251, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: [../third_party/gloo/gloo/transport/tcp/pair.cc:525] Read error [10.38.157.216]:48347: Connection reset by peer
/usr/local/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 21 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

**Comment by BibouOnAir** [comment]
Also, how to restart Applio in PaperSpace when it crashes.
I am always forced to restart a blank machine
