### ISSUE TITLE
[BUG] Too little data for declared Content-Length (getting this with every audio)

### ISSUE THREAD

**Issue by ZeroCool22** [IAHispano/Applio#576]
**Before You Report a Bug**
Reporting a bug is essential for us to improve our service, but we need detailed information to address the issue effectively. Since every computer setup is unique, there can be various reasons behind a bug. Before reporting, consider potential causes and provide as much detail as possible to help us understand the problem.

**Bug Description**
```
Theme Loaded: Applio
Running on local URL:  http://127.0.0.1:6969

To create a public link, set `share=True` in `launch()`.
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Applio-3.2.2\env\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 398, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Applio-3.2.2\env\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
  File "C:\Applio-3.2.2\env\lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Applio-3.2.2\env\lib\site-packages\starlette\applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Applio-3.2.2\env\lib\site-packages\starlette\middleware\errors.py", line 186, in __call__
    raise exc
  File "C:\Applio-3.2.2\env\lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "C:\Applio-3.2.2\env\lib\site-packages\gradio\route_utils.py", line 714, in __call__
    await self.app(scope, receive, send)
  File "C:\Applio-3.2.2\env\lib\site-packages\starlette\middleware\exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Applio-3.2.2\env\lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "C:\Applio-3.2.2\env\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Applio-3.2.2\env\lib\site-packages\starlette\routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Applio-3.2.2\env\lib\site-packages\starlette\routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "C:\Applio-3.2.2\env\lib\site-packages\starlette\routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "C:\Applio-3.2.2\env\lib\site-packages\starlette\routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Applio-3.2.2\env\lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "C:\Applio-3.2.2\env\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Applio-3.2.2\env\lib\site-packages\starlette\routing.py", line 75, in app
    await response(scope, receive, send)
  File "C:\Applio-3.2.2\env\lib\site-packages\starlette\responses.py", line 352, in __call__
    await send(
  File "C:\Applio-3.2.2\env\lib\site-packages\starlette\_exception_handler.py", line 50, in sender
    await send(message)
  File "C:\Applio-3.2.2\env\lib\site-packages\starlette\_exception_handler.py", line 50, in sender
    await send(message)
  File "C:\Applio-3.2.2\env\lib\site-packages\starlette\middleware\errors.py", line 161, in _send
    await send(message)
  File "C:\Applio-3.2.2\env\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 502, in send
    output = self.conn.send(event=h11.EndOfMessage())
  File "C:\Applio-3.2.2\env\lib\site-packages\h11\_connection.py", line 512, in send
    data_list = self.send_with_data_passthrough(event)
  File "C:\Applio-3.2.2\env\lib\site-packages\h11\_connection.py", line 545, in send_with_data_passthrough
    writer(event, data_list.append)
  File "C:\Applio-3.2.2\env\lib\site-packages\h11\_writers.py", line 67, in __call__
    self.send_eom(event.headers, write)
  File "C:\Applio-3.2.2\env\lib\site-packages\h11\_writers.py", line 96, in send_eom
    raise LocalProtocolError("Too little data for declared Content-Length")
h11._util.LocalProtocolError: Too little data for declared Content-Length
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Applio-3.2.2\env\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 398, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Applio-3.2.2\env\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
  File "C:\Applio-3.2.2\env\lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Applio-3.2.2\env\lib\site-packages\starlette\applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Applio-3.2.2\env\lib\site-packages\starlette\middleware\errors.py", line 186, in __call__
    raise exc
  File "C:\Applio-3.2.2\env\lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "C:\Applio-3.2.2\env\lib\site-packages\gradio\route_utils.py", line 714, in __call__
    await self.app(scope, receive, send)
  File "C:\Applio-3.2.2\env\lib\site-packages\starlette\middleware\exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Applio-3.2.2\env\lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "C:\Applio-3.2.2\env\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Applio-3.2.2\env\lib\site-packages\starlette\routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Applio-3.2.2\env\lib\site-packages\starlette\routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "C:\Applio-3.2.2\env\lib\site-packages\starlette\routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "C:\Applio-3.2.2\env\lib\site-packages\starlette\routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Applio-3.2.2\env\lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "C:\Applio-3.2.2\env\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Applio-3.2.2\env\lib\site-packages\starlette\routing.py", line 75, in app
    await response(scope, receive, send)
  File "C:\Applio-3.2.2\env\lib\site-packages\starlette\responses.py", line 352, in __call__
    await send(
  File "C:\Applio-3.2.2\env\lib\site-packages\starlette\_exception_handler.py", line 50, in sender
    await send(message)
  File "C:\Applio-3.2.2\env\lib\site-packages\starlette\_exception_handler.py", line 50, in sender
    await send(message)
  File "C:\Applio-3.2.2\env\lib\site-packages\starlette\middleware\errors.py", line 161, in _send
    await send(message)
  File "C:\Applio-3.2.2\env\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 502, in send
    output = self.conn.send(event=h11.EndOfMessage())
  File "C:\Applio-3.2.2\env\lib\site-packages\h11\_connection.py", line 512, in send
    data_list = self.send_with_data_passthrough(event)
  File "C:\Applio-3.2.2\env\lib\site-packages\h11\_connection.py", line 545, in send_with_data_passthrough
    writer(event, data_list.append)
  File "C:\Applio-3.2.2\env\lib\site-packages\h11\_writers.py", line 67, in __call__
    self.send_eom(event.headers, write)
  File "C:\Applio-3.2.2\env\lib\site-packages\h11\_writers.py", line 96, in send_eom
    raise LocalProtocolError("Too little data for declared Content-Length")
h11._util.LocalProtocolError: Too little data for declared Content-Length
```

**Steps to Reproduce**
Outline the steps to replicate the issue:
Open an audio.

**Expected Behavior**
Describe what you expected to happen.

**Assets**

https://github.com/user-attachments/assets/12f7ef64-f277-47c0-823f-0ba6bfddc727

**Desktop Details:**
- Operating System: [e.g., Windows 10]
- Browser: [e.g., FireFox, Edge]

**Additional Context**
Any additional information that might be relevant to the issue.

**Comment by blaisewf** [comment]
thats most a gradio bug, you should report it there
