### ISSUE TITLE
run-applio.bat open empty console titles Select Applio

### ISSUE THREAD

**Issue by erikobox** [IAHispano/Applio#615]
run-applio.bat open empty console titles Select Applio

**Comment by erikobox** [comment]
Now it just says Theme Loaded: Applio and nothing happens, ctrl + c doesn’t help.

**Comment by erikobox** [comment]
On ctrl + c it sayc

```
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\AI\Applio\app.py", line 92, in <module>
    download_tab()
  File "C:\AI\Applio\tabs\download\download.py", line 166, in download_tab
    choices=get_pretrained_list(),
  File "C:\AI\Applio\tabs\download\download.py", line 81, in get_pretrained_list
    data = fetch_pretrained_data()
  File "C:\AI\Applio\tabs\download\download.py", line 75, in fetch_pretrained_data
    response = requests.get(json_url)
  File "C:\AI\Applio\env\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "C:\AI\Applio\env\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\AI\Applio\env\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\AI\Applio\env\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\AI\Applio\env\lib\site-packages\requests\adapters.py", line 564, in send
    resp = conn.urlopen(
  File "C:\AI\Applio\env\lib\site-packages\urllib3\connectionpool.py", line 789, in urlopen
    response = self._make_request(
  File "C:\AI\Applio\env\lib\site-packages\urllib3\connectionpool.py", line 466, in _make_request
    self._validate_conn(conn)
  File "C:\AI\Applio\env\lib\site-packages\urllib3\connectionpool.py", line 1095, in _validate_conn
    conn.connect()
  File "C:\AI\Applio\env\lib\site-packages\urllib3\connection.py", line 615, in connect
    self.sock = sock = self._new_conn()
  File "C:\AI\Applio\env\lib\site-packages\urllib3\connection.py", line 196, in _new_conn
    sock = connection.create_connection(
  File "C:\AI\Applio\env\lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    sock.connect(sa)
KeyboardInterrupt
```

**Comment by Vidalnt** [comment]
> It finally running. It is not showing anything when you start run-applio.bat. No info in console for 10 minutes. And then working.
you don't see anything like this?
![image](https://github.com/user-attachments/assets/6a8d5435-e645-41b7-9f12-652131216779)

**Comment by erikobox** [comment]
> > It finally running. It is not showing anything when you start run-applio.bat. No info in console for 10 minutes. And then working.
> 
> you don't see anything like this? ![image](https://private-user-images.githubusercontent.com/102625768/359720985-6a8d5435-e645-41b7-9f12-652131216779.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyMDYwMTEsIm5iZiI6MTcyNDIwNTcxMSwicGF0aCI6Ii8xMDI2MjU3NjgvMzU5NzIwOTg1LTZhOGQ1NDM1LWU2NDUtNDFiNy05ZjEyLTY1MjEzMTIxNjc3OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMVQwMjAxNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZTk3ZGNlYWRmMjk3MzQ5ZjI0YjFmZmEzN2JlZmFlZDM0Yjc2MzQ2NDViZDBhYWMwZmU5MmQ0MWRhODcxZGYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cLZ-CMMz7GnOWXx6T5m0wPDkn6m6kVtKNNSFYAjJ8EE)

no, after 10-15 minutes i see only the last 2 rows. Every time I run it, this happens.
