### ISSUE TITLE
[BUG?]Error in inference function: use_f0

### ISSUE THREAD

**Issue by lenore-puwawa** [IAHispano/Applio#624]
English is not my first language. I use Google Translate. Sorry.

**Bug Description**
When attempting to convert from the Inference tab, a use_f0 error occurs and conversion is not possible.

**Steps to Reproduce**

Outline the steps to replicate the issue:
1. Register the pth file in the logs directory.
2. Click the Inference tab and then click the Refresh button.
3. Select the pth file registered in the logs directory, and do not set the index file.
4. Drag and drop the audio file you want to convert (file extension is wav).
5. Because the model uses japanese-hubert-base for embedding, change the embedded model to japanese-hubert-base and click the Convert button. An error occurs.

**Expected Behavior**
The conversion should be completed without errors.

**Assets**
none.

**Desktop Details:**
- Operating System: Windows 11
- Browser: edge
- GPU: RTX4070ti Super

**Additional Context**
The japanese-hubert-base model created with Applio did not result in an error.
Also, with the japanese-hubert-base model created with Applio, there was no error when no index file was set.
The model that caused the error this time was one that used japanese-hubert-base, created with ddPn08/rvc-webui(https://github.com/ddPn08/rvc-webui).
Perhaps the model created with Applio has unique information embedded in the pth file, and this information is missing, causing this error?

**Comment by blaisewf** [comment]
Could you use ChatGPT to better translate your problem and help you better? Maybe an attached video would also be useful.

**Comment by lenore-puwawa** [comment]
I used Bing/Copilot.

Sorry, I will only state the facts, excluding my imagination.
・Performed voice conversion using an RVC model created with ddPn08/rvc-webui.
・This RVC model uses Japanese-hubert-base.
・After pressing the conversion button, a conversion error occurred in the browser.
・The following message was output to the console:
`Traceback (most recent call last):
  File "C:\Users\lenore\Desktop\Applio-3.2.4\env\lib\site-packages\gradio\queueing.py", line 532, in process_events
    response = await route_utils.call_process_api(
  File "C:\Users\lenore\Desktop\Applio-3.2.4\env\lib\site-packages\gradio\route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\lenore\Desktop\Applio-3.2.4\env\lib\site-packages\gradio\blocks.py", line 1923, in process_api
    result = await self.call_function(
  File "C:\Users\lenore\Desktop\Applio-3.2.4\env\lib\site-packages\gradio\blocks.py", line 1509, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\lenore\Desktop\Applio-3.2.4\env\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\Users\lenore\Desktop\Applio-3.2.4\env\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "C:\Users\lenore\Desktop\Applio-3.2.4\env\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "C:\Users\lenore\Desktop\Applio-3.2.4\env\lib\site-packages\gradio\utils.py", line 832, in wrapper
    response = f(*args, **kwargs)
  File "C:\Users\lenore\Desktop\Applio-3.2.4\core.py", line 143, in run_batch_infer_script
    infer_pipeline.convert_audio(
  File "C:\Users\lenore\Desktop\Applio-3.2.4\rvc\infer\infer.py", line 173, in convert_audio
    self.get_vc(model_path, sid)
  File "C:\Users\lenore\Desktop\Applio-3.2.4\rvc\infer\infer.py", line 322, in get_vc
    self.setup_network()
  File "C:\Users\lenore\Desktop\Applio-3.2.4\rvc\infer\infer.py", line 364, in setup_network
    self.net_g = Synthesizer(
TypeError: __init__() got multiple values for argument 'use_f0'`

**Comment by blaisewf** [comment]
could you send me the model?

**Comment by blaisewf** [comment]
the model info seems right i don't know exactly what's your issue, you should try to retrain your model on applio since that repo is pretty old

**Comment by lenore-puwawa** [comment]
Understood. I will proceed with retraining on Applio.
Thank you for your time.
I look forward to the future of Applio!
