### ISSUE TITLE
tried using TTS and this error showed up

### ISSUE THREAD

**Issue by Izolovi4** [IAHispano/Applio#654]
https://github.com/user-attachments/assets/52a21cba-cb49-461e-926d-0416eab43c5a

full text of an error:

> To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "C:\Users\asdf\Desktop\appl\rvc\lib\tools\tts.py", line 20, in <module>
    asyncio.run(main())
  File "C:\Users\asdf\Desktop\appl\env\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\asdf\Desktop\appl\env\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\asdf\Desktop\appl\rvc\lib\tools\tts.py", line 15, in main
    await edge_tts.Communicate(text, voice, rate=rates).save(output_file)
  File "C:\Users\asdf\Desktop\appl\env\lib\site-packages\edge_tts\communicate.py", line 279, in __init__
    raise ValueError(f"Invalid voice '{voice}'.")
ValueError: Invalid voice 'None'.
C:\Users\asdf\Desktop\appl\env\lib\site-packages\transformers\tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
2024-08-30 16:41:59 | INFO | faiss.loader | Loading faiss with AVX2 support.
2024-08-30 16:41:59 | INFO | faiss.loader | Could not load library with AVX2 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")
2024-08-30 16:41:59 | INFO | faiss.loader | Loading faiss.
2024-08-30 16:41:59 | INFO | faiss.loader | Successfully loaded faiss.
Traceback (most recent call last):
  File "C:\Users\asdf\Desktop\appl\env\lib\site-packages\gradio\queueing.py", line 532, in process_events
    response = await route_utils.call_process_api(
  File "C:\Users\asdf\Desktop\appl\env\lib\site-packages\gradio\route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\asdf\Desktop\appl\env\lib\site-packages\gradio\blocks.py", line 1923, in process_api
    result = await self.call_function(
  File "C:\Users\asdf\Desktop\appl\env\lib\site-packages\gradio\blocks.py", line 1509, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\asdf\Desktop\appl\env\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\Users\asdf\Desktop\appl\env\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "C:\Users\asdf\Desktop\appl\env\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "C:\Users\asdf\Desktop\appl\env\lib\site-packages\gradio\utils.py", line 832, in wrapper
    response = f(*args, **kwargs)
  File "C:\Users\asdf\Desktop\appl\core.py", line 216, in run_tts_script
    infer_pipeline.convert_audio(
  File "C:\Users\asdf\Desktop\appl\rvc\infer\infer.py", line 173, in convert_audio
    self.get_vc(model_path, sid)
  File "C:\Users\asdf\Desktop\appl\rvc\infer\infer.py", line 322, in get_vc
    self.setup_network()
  File "C:\Users\asdf\Desktop\appl\rvc\infer\infer.py", line 358, in setup_network
    self.tgt_sr = self.cpt["config"][-1]
KeyError: 'config'

**Comment by blaisewf** [comment]
you cant use a G or D model, you must use the checkpoints, the format is like name_epochs_steps.pth

**Comment by Izolovi4** [comment]
> you cant use a G or D model, you must use the checkpoints, the format is like name_epochs_steps.pth
where are they saved?
