### ISSUE TITLE
[Bug]: Voice Blender error - too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by embis0126** [IAHispano/Applio#706]
### Project Version

3.2.5

### Platform and OS Version

Windows 11 64-bit

### Affected Devices

All

### What happened?

```
Traceback (most recent call last):
  File "C:\Software\Applio\env\lib\site-packages\gradio\queueing.py", line 532, in process_events
    response = await route_utils.call_process_api(
  File "C:\Software\Applio\env\lib\site-packages\gradio\route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Software\Applio\env\lib\site-packages\gradio\blocks.py", line 1923, in process_api
    result = await self.call_function(
  File "C:\Software\Applio\env\lib\site-packages\gradio\blocks.py", line 1509, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Software\Applio\env\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\Software\Applio\env\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "C:\Software\Applio\env\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "C:\Software\Applio\env\lib\site-packages\gradio\utils.py", line 832, in wrapper
    response = f(*args, **kwargs)
  File "C:\Software\Applio\core.py", line 550, in run_model_blender_script
    message, model_blended = model_blender(model_name, pth_path_1, pth_path_2, ratio)
ValueError: too many values to unpack (expected 2)
Traceback (most recent call last):
  File "C:\Software\Applio\env\lib\site-packages\gradio\queueing.py", line 532, in process_events
    response = await route_utils.call_process_api(
  File "C:\Software\Applio\env\lib\site-packages\gradio\route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Software\Applio\env\lib\site-packages\gradio\blocks.py", line 1923, in process_api
    result = await self.call_function(
  File "C:\Software\Applio\env\lib\site-packages\gradio\blocks.py", line 1509, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Software\Applio\env\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\Software\Applio\env\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "C:\Software\Applio\env\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "C:\Software\Applio\env\lib\site-packages\gradio\utils.py", line 832, in wrapper
    response = f(*args, **kwargs)
  File "C:\Software\Applio\core.py", line 550, in run_model_blender_script
    message, model_blended = model_blender(model_name, pth_path_1, pth_path_2, ratio)
ValueError: too many values to unpack (expected 2)
Traceback (most recent call last):
  File "C:\Software\Applio\env\lib\site-packages\gradio\queueing.py", line 532, in process_events
    response = await route_utils.call_process_api(
  File "C:\Software\Applio\env\lib\site-packages\gradio\route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Software\Applio\env\lib\site-packages\gradio\blocks.py", line 1923, in process_api
    result = await self.call_function(
  File "C:\Software\Applio\env\lib\site-packages\gradio\blocks.py", line 1509, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Software\Applio\env\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\Software\Applio\env\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "C:\Software\Applio\env\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "C:\Software\Applio\env\lib\site-packages\gradio\utils.py", line 832, in wrapper
    response = f(*args, **kwargs)
  File "C:\Software\Applio\core.py", line 550, in run_model_blender_script
    message, model_blended = model_blender(model_name, pth_path_1, pth_path_2, ratio)
ValueError: too many values to unpack (expected 2)
Traceback (most recent call last):
  File "C:\Software\Applio\env\lib\site-packages\gradio\queueing.py", line 532, in process_events
    response = await route_utils.call_process_api(
  File "C:\Software\Applio\env\lib\site-packages\gradio\route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Software\Applio\env\lib\site-packages\gradio\blocks.py", line 1923, in process_api
    result = await self.call_function(
  File "C:\Software\Applio\env\lib\site-packages\gradio\blocks.py", line 1509, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Software\Applio\env\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\Software\Applio\env\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "C:\Software\Applio\env\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "C:\Software\Applio\env\lib\site-packages\gradio\utils.py", line 832, in wrapper
    response = f(*args, **kwargs)
  File "C:\Software\Applio\core.py", line 550, in run_model_blender_script
    message, model_blended = model_blender(model_name, pth_path_1, pth_path_2, ratio)
ValueError: too many values to unpack (expected 2)
```

### Steps to reproduce

1. Open Applio
2. Go to Voice Blender
3. Try to blend two models
4. ???

### Expected behavior

For the models to blend

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/5dde2fb8-d7ca-477f-a6ea-f07d6af58476)

**Comment by blaisewf** [comment]
make sure that both models have the same sample rate

**Comment by embis0126** [comment]
they do

**Comment by blaisewf** [comment]
could you please share the models with me to try it?

**Comment by elysiumspark** [comment]
@embis0126 - Also make sure you have a name in the "Model Name" field.  I was getting this same error, then realized I was an idiot... lol
