### ISSUE TITLE
[Bug]: ERROR: Exception in ASGI application (duplicate)

### ISSUE THREAD

**Issue by Kelthic** [IAHispano/Applio#720]
### Project Version

3.2.5

### Platform and OS Version

Windows 11, 64 Bit

### Affected Devices

Windows

### What happened?

```
Theme Applio successfully loaded.
Running on local URL:  http://127.0.0.1:6969

To create a public link, set `share=True` in `launch()`.
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "D:\Software\ApplioRVC\Applio-3.0.6\env\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "D:\Software\ApplioRVC\Applio-3.0.6\env\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
  File "D:\Software\ApplioRVC\Applio-3.0.6\env\lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "D:\Software\ApplioRVC\Applio-3.0.6\env\lib\site-packages\starlette\applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\Software\ApplioRVC\Applio-3.0.6\env\lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
    raise exc
  File "D:\Software\ApplioRVC\Applio-3.0.6\env\lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "D:\Software\ApplioRVC\Applio-3.0.6\env\lib\site-packages\gradio\route_utils.py", line 714, in __call__
    await self.app(scope, receive, send)
  File "D:\Software\ApplioRVC\Applio-3.0.6\env\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "D:\Software\ApplioRVC\Applio-3.0.6\env\lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "D:\Software\ApplioRVC\Applio-3.0.6\env\lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "D:\Software\ApplioRVC\Applio-3.0.6\env\lib\site-packages\starlette\routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\Software\ApplioRVC\Applio-3.0.6\env\lib\site-packages\starlette\routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "D:\Software\ApplioRVC\Applio-3.0.6\env\lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "D:\Software\ApplioRVC\Applio-3.0.6\env\lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "D:\Software\ApplioRVC\Applio-3.0.6\env\lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "D:\Software\ApplioRVC\Applio-3.0.6\env\lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "D:\Software\ApplioRVC\Applio-3.0.6\env\lib\site-packages\starlette\routing.py", line 74, in app
    await response(scope, receive, send)
  File "D:\Software\ApplioRVC\Applio-3.0.6\env\lib\site-packages\starlette\responses.py", line 338, in __call__
    await send(
  File "D:\Software\ApplioRVC\Applio-3.0.6\env\lib\site-packages\starlette\_exception_handler.py", line 48, in sender
    await send(message)
  File "D:\Software\ApplioRVC\Applio-3.0.6\env\lib\site-packages\starlette\_exception_handler.py", line 48, in sender
    await send(message)
  File "D:\Software\ApplioRVC\Applio-3.0.6\env\lib\site-packages\starlette\middleware\errors.py", line 162, in _send
    await send(message)
  File "D:\Software\ApplioRVC\Applio-3.0.6\env\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 510, in send
    output = self.conn.send(event=h11.EndOfMessage())
  File "D:\Software\ApplioRVC\Applio-3.0.6\env\lib\site-packages\h11\_connection.py", line 512, in send
    data_list = self.send_with_data_passthrough(event)
  File "D:\Software\ApplioRVC\Applio-3.0.6\env\lib\site-packages\h11\_connection.py", line 545, in send_with_data_passthrough
    writer(event, data_list.append)
  File "D:\Software\ApplioRVC\Applio-3.0.6\env\lib\site-packages\h11\_writers.py", line 67, in __call__
    self.send_eom(event.headers, write)
  File "D:\Software\ApplioRVC\Applio-3.0.6\env\lib\site-packages\h11\_writers.py", line 96, in send_eom
    raise LocalProtocolError("Too little data for declared Content-Length")
h11._util.LocalProtocolError: Too little data for declared Content-Length
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "D:\Software\ApplioRVC\Applio-3.0.6\env\lib\site-packages\pydantic\type_adapter.py", line 270, in _init_core_attrs
    self._core_schema = _getattr_no_parents(self._type, '__pydantic_core_schema__')
  File "D:\Software\ApplioRVC\Applio-3.0.6\env\lib\site-packages\pydantic\type_adapter.py", line 112, in _getattr_no_parents
    raise AttributeError(attribute)
AttributeError: __pydantic_core_schema__

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Software\ApplioRVC\Applio-3.0.6\env\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "D:\Software\ApplioRVC\Applio-3.0.6\env\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
  File "D:\Software\ApplioRVC\Applio-3.0.6\env\lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "D:\Software\ApplioRVC\Applio-3.0.6\env\lib\site-packages\starlette\applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\Software\ApplioRVC\Applio-3.0.6\env\lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
    raise exc
  File "D:\Software\ApplioRVC\Applio-3.0.6\env\lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "D:\Software\ApplioRVC\Applio-3.0.6\env\lib\site-packages\gradio\route_utils.py", line 720, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "D:\Software\ApplioRVC\Applio-3.0.6\env\lib\site-packages\gradio\route_utils.py", line 736, in simple_response
    await self.app(scope, receive, send)
  File "D:\Software\ApplioRVC\Applio-3.0.6\env\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "D:\Software\ApplioRVC\Applio-3.0.6\env\lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "D:\Software\ApplioRVC\Applio-3.0.6\env\lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "D:\Software\ApplioRVC\Applio-3.0.6\env\lib\site-packages\starlette\routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\Software\ApplioRVC\Applio-3.0.6\env\lib\site-packages\starlette\routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "D:\Software\ApplioRVC\Applio-3.0.6\env\lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "D:\Software\ApplioRVC\Applio-3.0.6\env\lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "D:\Software\ApplioRVC\Applio-3.0.6\env\lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "D:\Software\ApplioRVC\Applio-3.0.6\env\lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "D:\Software\ApplioRVC\Applio-3.0.6\env\lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
  File "D:\Software\ApplioRVC\Applio-3.0.6\env\lib\site-packages\fastapi\routing.py", line 291, in app
    solved_result = await solve_dependencies(
  File "D:\Software\ApplioRVC\Applio-3.0.6\env\lib\site-packages\fastapi\dependencies\utils.py", line 656, in solve_dependencies
    ) = await request_body_to_args(  # body_params checked above
  File "D:\Software\ApplioRVC\Applio-3.0.6\env\lib\site-packages\fastapi\dependencies\utils.py", line 881, in request_body_to_args
    fields_to_extract = get_cached_model_fields(first_field.type_)
  File "D:\Software\ApplioRVC\Applio-3.0.6\env\lib\site-packages\fastapi\_compat.py", line 657, in get_cached_model_fields
    return get_model_fields(model)
  File "D:\Software\ApplioRVC\Applio-3.0.6\env\lib\site-packages\fastapi\_compat.py", line 284, in get_model_fields
    return [
  File "D:\Software\ApplioRVC\Applio-3.0.6\env\lib\site-packages\fastapi\_compat.py", line 285, in <listcomp>
    ModelField(field_info=field_info, name=name)
  File "<string>", line 6, in __init__
  File "D:\Software\ApplioRVC\Applio-3.0.6\env\lib\site-packages\fastapi\_compat.py", line 110, in __post_init__
    self._type_adapter: TypeAdapter[Any] = TypeAdapter(
  File "D:\Software\ApplioRVC\Applio-3.0.6\env\lib\site-packages\pydantic\type_adapter.py", line 257, in __init__
    self._init_core_attrs(rebuild_mocks=False)
  File "D:\Software\ApplioRVC\Applio-3.0.6\env\lib\site-packages\pydantic\type_adapter.py", line 135, in wrapped
    return func(self, *args, **kwargs)
  File "D:\Software\ApplioRVC\Applio-3.0.6\env\lib\site-packages\pydantic\type_adapter.py", line 277, in _init_core_attrs
    self._core_schema = _get_schema(self._type, config_wrapper, parent_depth=self._parent_depth)
  File "D:\Software\ApplioRVC\Applio-3.0.6\env\lib\site-packages\pydantic\type_adapter.py", line 95, in _get_schema
    schema = gen.generate_schema(type_)
  File "D:\Software\ApplioRVC\Applio-3.0.6\env\lib\site-packages\pydantic\_internal\_generate_schema.py", line 655, in generate_schema
    schema = self._generate_schema_inner(obj)
  File "D:\Software\ApplioRVC\Applio-3.0.6\env\lib\site-packages\pydantic\_internal\_generate_schema.py", line 908, in _generate_schema_inner
    return self._annotated_schema(obj)
  File "D:\Software\ApplioRVC\Applio-3.0.6\env\lib\site-packages\pydantic\_internal\_generate_schema.py", line 2028, in _annotated_schema
    schema = self._apply_annotations(source_type, annotations)
  File "D:\Software\ApplioRVC\Applio-3.0.6\env\lib\site-packages\pydantic\_internal\_generate_schema.py", line 2107, in _apply_annotations
    schema = get_inner_schema(source_type)
  File "D:\Software\ApplioRVC\Applio-3.0.6\env\lib\site-packages\pydantic\_internal\_schema_generation_shared.py", line 83, in __call__
    schema = self._handler(source_type)
  File "D:\Software\ApplioRVC\Applio-3.0.6\env\lib\site-packages\pydantic\_internal\_generate_schema.py", line 2189, in new_handler
    schema = metadata_get_schema(source, get_inner_schema)
  File "D:\Software\ApplioRVC\Applio-3.0.6\env\lib\site-packages\pydantic\_internal\_generate_schema.py", line 2185, in <lambda>
    lambda source, handler: handler(source)
  File "D:\Software\ApplioRVC\Applio-3.0.6\env\lib\site-packages\pydantic\_internal\_schema_generation_shared.py", line 83, in __call__
    schema = self._handler(source_type)
  File "D:\Software\ApplioRVC\Applio-3.0.6\env\lib\site-packages\pydantic\_internal\_generate_schema.py", line 2088, in inner_handler
    schema = self._generate_schema_inner(obj)
  File "D:\Software\ApplioRVC\Applio-3.0.6\env\lib\site-packages\pydantic\_internal\_generate_schema.py", line 929, in _generate_schema_inner
    return self.match_type(obj)
  File "D:\Software\ApplioRVC\Applio-3.0.6\env\lib\site-packages\pydantic\_internal\_generate_schema.py", line 1029, in match_type
    return self._match_generic_type(obj, origin)
  File "D:\Software\ApplioRVC\Applio-3.0.6\env\lib\site-packages\pydantic\_internal\_generate_schema.py", line 1058, in _match_generic_type
    return self._union_schema(obj)
  File "D:\Software\ApplioRVC\Applio-3.0.6\env\lib\site-packages\pydantic\_internal\_generate_schema.py", line 1378, in _union_schema
    choices.append(self.generate_schema(arg))
  File "D:\Software\ApplioRVC\Applio-3.0.6\env\lib\site-packages\pydantic\_internal\_generate_schema.py", line 655, in generate_schema
    schema = self._generate_schema_inner(obj)
  File "D:\Software\ApplioRVC\Applio-3.0.6\env\lib\site-packages\pydantic\_internal\_generate_schema.py", line 929, in _generate_schema_inner
    return self.match_type(obj)
  File "D:\Software\ApplioRVC\Applio-3.0.6\env\lib\site-packages\pydantic\_internal\_generate_schema.py", line 1038, in match_type
    return self._unknown_type_schema(obj)
  File "D:\Software\ApplioRVC\Applio-3.0.6\env\lib\site-packages\pydantic\_internal\_generate_schema.py", line 558, in _unknown_type_schema
    raise PydanticSchemaGenerationError(
pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <class 'starlette.requests.Request'>. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.

If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__` then you likely need to call `handler.generate_schema(<some type>)` since we do not call `__get_pydantic_core_schema__` on `<some type>` otherwise to avoid infinite recursion.

For further information visit https://errors.pydantic.dev/2.9/u/schema-for-unknown-type
```

Clean Windows 11, i got this shXt in 3.2.5 version 

**Any solutions instead downgrade?**

### Steps to reproduce

1. Run Applio
2. Open Tab in Browser
3. Click any button in Applio Tab and catch this error 
...

### Expected behavior

Just get run Applio

### Additional Information

I catch this problem instantly after installing and running (these things was without any troubles)

**Comment by blaisewf** [comment]
answered this like 10 times on recent issues, on github you can find a fix

**Comment by Kelthic** [comment]
Solution (works to me and thanks to noobies5663 from Discord):

Put it in **run-applio.bat**

```
@echo off
setlocal
title Applio

if not exist env (
    echo Please run 'run-install.bat' first to set up the environment.
    pause
    exit /b 1
)

env\python.exe -m pip install pydantic==2.8.2 fastapi==0.112.0 starlette==0.37.2 gradio==4.43.0
echo.
pause
```

After that use default **run-applio.bat**
