### ISSUE TITLE
[Bug]: training error

### ISSUE THREAD

**Issue by sipie800** [IAHispano/Applio#738]
### Project Version

325

### Platform and OS Version

win10

### Affected Devices

pc

### What happened?

Traceback (most recent call last):
  File "T:\applio3.25\rvc\train\train.py", line 413, in run
    _, _, _, epoch_str = load_checkpoint(
  File "T:\applio3.25\rvc\train\utils.py", line 44, in load_checkpoint
    assert os.path.isfile(
  File "T:\applio3.25\env\lib\genericpath.py", line 30, in isfile
    st = os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "T:\applio3.25\env\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "T:\applio3.25\env\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "T:\applio3.25\rvc\train\train.py", line 429, in run
    net_g.module.load_state_dict(
  File "T:\applio3.25\env\lib\site-packages\torch\nn\modules\module.py", line 2152, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Synthesizer:
        Missing key(s) in state_dict: "dec.ups_and_resblocks.0.bias",

### Steps to reproduce

just use normal training

### Expected behavior

train

**Comment by sipie800** [comment]
I have cuda:0 and cuda:1 two GPUs. Once I choose both or only 0, it trains.
If I choose only 1, it fails loading the weight randomly. (1 or 2 of 10 times it works).
But that's just what I need. I use GPU 0 for main important work and 1 for running a regular training.

**Comment by AznamirWoW** [comment]
@sipie800 bigger error message?

I believe we've tested 3.2.5 in multi-gpu setup without any issues with "Pitch Guidance" checked. The error you're seeing seems the one caused by trying training without Pitch guidance. Please confirm.
