### ISSUE TITLE
[Bug]: Issue with Bitcrashing causing an issue with running the file. 

### ISSUE THREAD

**Issue by kineticdirt** [IAHispano/Applio#742]
### Project Version

3.2.5

### Platform and OS Version

Windows 11

### Affected Devices

No device

### What happened?

I'm having an issue regarding bitcrusher somehow crashing applio when selected for batch runs.

An error occurred during audio conversion: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. pedalboard_native.Bitcrush(bit_depth: float = 8)

Invoked with: kwargs: bit_depth=[{'__type__': 'update', 'visible': True}]
Traceback (most recent call last):
  File "C:\Users\***\Desktop\ApplioV3.2.5\rvc\infer\infer.py", line 497, in convert_audio
    audio_output_path = self.post_process_audio(
  File "C:\Users\***\Desktop\ApplioV3.2.5\rvc\infer\infer.py", line 211, in post_process_audio
    bitcrush = Bitcrush(bit_depth=bitcrush_bit_depth)
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. pedalboard_native.Bitcrush(bit_depth: float = 8)

Invoked with: kwargs: bit_depth=[{'__type__': 'update', 'visible': True}]

### Steps to reproduce

1. Simply run it with bitcrashing resulted in this error. For some reason its not giving the correct type. Found a solution which while inefficient, works. 
...

### Expected behavior

I expected it to work. In batch running, it completely fails outright and requires a full reboot (rerunning the .bat file).

### Additional Information

if bitcrush:
            if bitcrush_bit_depth == [{'__type__': 'update', 'visible': True}]:
                bit_depth = 8
                bitcrush = Bitcrush(bit_depth)
            else:
                bitcrush = Bitcrush(bit_depth=bitcrush_bit_depth)
            board.append(bitcrush)

Did some work to the applio files and created a simple hotfix for now.

For some reason the bitcrushbitdepth is returning a list of dictionaries??? [{'__type': 'update', 'visible': True}]

I presume this is due to the wrong data being assigned, but I don't have the technical knowhow to really 'fix' it.
This was in in the infer.py file

**Comment by kineticdirt** [comment]
The solution is included in the actual code above, but it is a very poor solution. It does stop the crashing 👍
