### ISSUE TITLE
[RuntimeError]: CUDA error: operation not supported CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect. For debugging consider passing CUDA_LAUNCH_BLOCKING=1. Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

### ISSUE THREAD

**Issue by abujr101** [IAHispano/Applio#764]
### Project Version

3.2.6

### Platform and OS Version

windows 11

### Affected Devices

Amd RX 580

### What happened?

i am, on amd gpu . my gpu shader ISA is GFx803. I follow all the instrustion for amd gpu . but i am getting this error when inferencing 

To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "D:\Applio-3.2.6\env\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "D:\Applio-3.2.6\env\lib\site-packages\gradio\route_utils.py", line 321, in call_process_api
    output = await app.get_blocks().process_api(
  File "D:\Applio-3.2.6\env\lib\site-packages\gradio\blocks.py", line 1935, in process_api
    result = await self.call_function(
  File "D:\Applio-3.2.6\env\lib\site-packages\gradio\blocks.py", line 1520, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "D:\Applio-3.2.6\env\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "D:\Applio-3.2.6\env\lib\site-packages\anyio\_backends\_asyncio.py", line 2405, in run_sync_in_worker_thread
    return await future
  File "D:\Applio-3.2.6\env\lib\site-packages\anyio\_backends\_asyncio.py", line 914, in run
    result = context.run(func, *args)
  File "D:\Applio-3.2.6\env\lib\site-packages\gradio\utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
  File "D:\Applio-3.2.6\core.py", line 192, in run_infer_script
    infer_pipeline.convert_audio(
  File "D:\Applio-3.2.6\rvc\infer\infer.py", line 254, in convert_audio
    self.get_vc(model_path, sid)
  File "D:\Applio-3.2.6\rvc\infer\infer.py", line 435, in get_vc
    self.setup_network()
  File "D:\Applio-3.2.6\rvc\infer\infer.py", line 487, in setup_network
    self.net_g.half() if self.config.is_half else self.net_g.float()
  File "D:\Applio-3.2.6\env\lib\site-packages\torch\nn\modules\module.py", line 1011, in half
    return self._apply(lambda t: t.half() if t.is_floating_point() else t)
  File "D:\Applio-3.2.6\env\lib\site-packages\torch\nn\modules\module.py", line 779, in _apply
    module._apply(fn)
  File "D:\Applio-3.2.6\env\lib\site-packages\torch\nn\modules\module.py", line 779, in _apply
    module._apply(fn)
  File "D:\Applio-3.2.6\env\lib\site-packages\torch\nn\modules\module.py", line 804, in _apply
    param_applied = fn(param)
  File "D:\Applio-3.2.6\env\lib\site-packages\torch\nn\modules\module.py", line 1011, in <lambda>
    return self._apply(lambda t: t.half() if t.is_floating_point() else t)
RuntimeError: CUDA error: operation not supported
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by AznamirWoW** [comment]
Try downgrading to torch 2.2.1. RX580 are quote old and do not support FP16.

`env\python -m pip install torch==2.2.1 torchvision==0.17.1 torchaudio==2.2.1 --index-url https://download.pytorch.org/whl/cu118`

**Comment by Kirasabi** [comment]
same issue at rtx 4070ti

**Comment by Jessegamer8k** [comment]
I have the same problem with the RX 6600 but it's on Windows 10

**Comment by fridolie** [comment]
yeah rx 7800 too should buy nvidia ;/

**Comment by AznamirWoW** [comment]
> yeah rx 7800 too should buy nvidia ;/

you probably did not follow the readme

**Comment by fridolie** [comment]
Why nobody can make zip with work model amd card . Yea i understand rocm must install and zula env. I follow readme and even install 5 version applio. Error gradio or CUDA_LAUNCH_BLOCKING=1 . My old laptop with 1660 ti run this without problem. Now i regret buy AMD dont think this gonna have big problems with everythink. I even follow with your maybe when this gonna be easer for me. Maybe somone can record exaple how to install for AMD in youtube or something else. Im beginner with this so sorry if i dont undertand some shit.

[https://github.com/IAHispano/Applio/issues/503](url)

**Comment by AznamirWoW** [comment]
> Im beginner with this so sorry if i dont undertand some shit.

Just follow the [readme](https://docs.applio.org/getting-started/installation#amd-gpu-support-windows)

**Comment by AznamirWoW** [comment]
One possibility is that the pip install does not replace the torch cu121. You should've seen that while trying to install it.

in that case run `env\python -m pip uninstall torch torchvision torchaudio` prior to installing torch cu118

**Comment by blaisewf** [comment]
I was able to reproduce a similar error inferring a long audio

**Comment by AznamirWoW** [comment]
The fix for "RuntimeError: CUDA error: operation not supported
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect." is uninstalling cu121 torch and re-installing cu118

Zluda does not work with cu121.

**Comment by veryscaryone** [comment]
I was getting this error. What fixed it for me was adding the rocm bin address to Path under system variables. Even though rocm is already there as HIP it needed to be added to path for me to get it to work.
