### ISSUE TITLE
[Bug]: VRAM OOM after 1b935bd9764f5b6e80d6344907f02291581b1a35

### ISSUE THREAD

**Issue by Chilluminati91** [IAHispano/Applio#780]
### Project Version

After 1b935bd9764f5b6e80d6344907f02291581b1a35

### Platform and OS Version

Windows 11 64Bit

### Affected Devices

/

### What happened?

Commit after 1b935bd9764f5b6e80d6344907f02291581b1a35 eats up VRAM while training.
Batch size 6 takes ca. 6GB of VRAM before, on the latest version it runs up to 16GB for the first epoch and then OOM on a 24GB RTX 3090.

### Steps to reproduce

1. git pull
2. start training
3. keep an eye on your VRAM usage

### Expected behavior

Should take only about 1/3 of the VRAM on training.

**Comment by Chilluminati91** [comment]
```
Running on local URL:  http://0.0.0.0:6969

To create a public link, set `share=True` in `launch()`.
Sync graph is now activated! With sync graph enabled, the model undergoes a single epoch of training. Once the graphs are synchronized, training proceeds for the previously specified number of epochs.
Starting training...
Loaded pretrained (G) 'rvc\models\pretraineds\pretraineds_custom\G-f040k-TITAN-Medium.pth'
Loaded pretrained (D) 'rvc\models\pretraineds\pretraineds_custom\D-f040k-TITAN-Medium.pth'
Process Process-1:
Traceback (most recent call last):
  File "C:\Users\xxx\Documents\machine_learning\audio_rvc-applio\env\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\xxx\Documents\machine_learning\audio_rvc-applio\env\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\xxx\Documents\machine_learning\audio_rvc-applio\rvc\train\train.py", line 494, in run
    train_and_evaluate(
  File "C:\Users\xxx\Documents\machine_learning\audio_rvc-applio\rvc\train\train.py", line 782, in train_and_evaluate
    o, *_ = net_g.infer(phone, phone_lengths, pitch, pitchf, sid)
  File "C:\Users\xxx\Documents\machine_learning\audio_rvc-applio\rvc\lib\algorithm\synthesizers.py", line 233, in infer
    o = self.dec(z * x_mask, nsff0, g=g)
  File "C:\Users\xxx\Documents\machine_learning\audio_rvc-applio\env\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\xxx\Documents\machine_learning\audio_rvc-applio\env\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\xxx\Documents\machine_learning\audio_rvc-applio\rvc\lib\algorithm\nsf.py", line 163, in forward
    [
  File "C:\Users\xxx\Documents\machine_learning\audio_rvc-applio\rvc\lib\algorithm\nsf.py", line 164, in <listcomp>
    resblock(x)
  File "C:\Users\xxx\Documents\machine_learning\audio_rvc-applio\env\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\xxx\Documents\machine_learning\audio_rvc-applio\env\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\xxx\Documents\machine_learning\audio_rvc-applio\rvc\lib\algorithm\residuals.py", line 45, in forward
    xt = torch.nn.functional.leaky_relu(x, LRELU_SLOPE)
  File "C:\Users\xxx\Documents\machine_learning\audio_rvc-applio\env\lib\site-packages\torch\nn\functional.py", line 1675, in leaky_relu
    result = torch._C._nn.leaky_relu(input, negative_slope)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 88.00 MiB. GPU
Traceback (most recent call last):
  File "C:\Users\xxx\Documents\machine_learning\audio_rvc-applio\rvc\train\train.py", line 1036, in <module>
    main()
  File "C:\Users\xxx\Documents\machine_learning\audio_rvc-applio\rvc\train\train.py", line 296, in main
    edit_config(model_config_file)
  File "C:\Users\xxx\Documents\machine_learning\audio_rvc-applio\rvc\train\train.py", line 285, in edit_config
    config_data["train"]["log_interval"] = steps
NameError: free variable 'steps' referenced before assignment in enclosing scope
```

**Comment by AznamirWoW** [comment]
What's the dataset size?

**Comment by Chilluminati91** [comment]
Roughly 25min, 130mb wav files. Commit that I stated above works fine at around 6GB VRAM usage.

**Comment by blaisewf** [comment]
at the start of the training, 100mb is not too much, you only have applio running?

**Comment by kro-ai** [comment]
I have noticed something related to this as well (I think).. training is INCREDIBLY slow after the new update. I have 10GB Vram, and I've been training successfully ever since I started using Applio like a year ago, but this latest update makes training so slow that It's almost not even worth it. It's incredibly annoying.

**Comment by AznamirWoW** [comment]
I'm testing with a previous version of torch. The recent training changes (adding audio sample output per epoch) should not have caused this issue.

**Comment by AznamirWoW** [comment]
fixed in https://github.com/IAHispano/Applio/blob/ce5864c9555977346edbc62037c00a688e2aead5/rvc/train/train.py
