### ISSUE TITLE
[Bug]: NameError: free variable 'steps' referenced before assignment in enclosing scope

### ISSUE THREAD

**Issue by Kuchiriel** [IAHispano/Applio#820]
### Project Version

3.2.6

### Platform and OS Version

Windows 11

### Affected Devices

Acer Nitro V 15

### What happened?

Traceback (most recent call last):
  File "C:\Applio-3.2.6\rvc\train\train.py", line 1030, in <module>
    main()
  File "C:\Applio-3.2.6\rvc\train\train.py", line 296, in main
    edit_config(model_config_file)
  File "C:\Applio-3.2.6\rvc\train\train.py", line 285, in edit_config
    config_data["train"]["log_interval"] = steps
NameError: free variable 'steps' referenced before assignment in enclosing scope

### Steps to reproduce

Train
Sampling Rate 48000
Model Architecture V2

Preprocess
Dataset Path C:/... (1h .wem audio files)

Audio cutting (check)
Noise Reduction (check) Strength 0,5
Process effects (check)

Extract Features
Pitch Guidance (check)
Pitch extraction algorithm rmvpe
Embedder Model contentvec
CPU Cores (auto)
GPU Number (auto)
GPU Information (auto)

Train
Batch Size (auto)
Save Every Epoch (2)
Total Epoch (20)
Save Only Latest (check)
Sync Graph (check)
Save Every Weights (check)
Cache Dataset in GPU (check)
Pretrained (check)
Pitch Guidance (check)
Overtraining Detector (check) 
Overtraining Threshold 5
GPU Number (auto)
GPU Information (auto)
Index Algorithm (auto)

### Expected behavior

Train, with default settings the issue do not happen

**Comment by Kuchiriel** [comment]
My bad:
The sample rate of the pretrain doesn't match the selected one
