### ISSUE TITLE
[Bug]: Error when training on Kaggle

### ISSUE THREAD

**Issue by Kuchiriel** [IAHispano/Applio#824]
### Project Version

Latest

### Platform and OS Version

Kaggle

### Affected Devices

Kaggle Latest Environment

### What happened?

Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/opt/conda/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/kaggle/working/program_ml/rvc/train/train.py", line 509, in run
    train_and_evaluate(
  File "/kaggle/working/program_ml/rvc/train/train.py", line 707, in train_and_evaluate
    scaler.scale(loss_disc).backward()
  File "/kaggle/tmp/.venv/lib/python3.10/site-packages/torch/_tensor.py", line 525, in backward
    torch.autograd.backward(
  File "/kaggle/tmp/.venv/lib/python3.10/site-packages/torch/autograd/__init__.py", line 267, in backward
    _engine_run_backward(
  File "/kaggle/tmp/.venv/lib/python3.10/site-packages/torch/autograd/graph.py", line 744, in _engine_run_backward
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: [../third_party/gloo/gloo/transport/tcp/pair.cc:534] Connection closed by peer [172.19.2.2]:48294
/opt/conda/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 42 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

### Steps to reproduce

Happens during training between 100 ~ 500 epochs

### Expected behavior

Continue the training without this error

**Comment by aris-py** [comment]
@Vidalnt

**Comment by blaisewf** [comment]
make sure that you have a gpu available, i'm unable to replicate

**Comment by Kuchiriel** [comment]
> make sure that you have a gpu available, i'm unable to replicate

I forgot to mention. I use 1h plus samples audio files for training. Based on the error it seems to be some thread or race condition error related to unix semaphores which I assume is the kernel from kaggle. I will try adjust those semaphores to see what happens. I saw the problem in other resource intense softwares.
