### ISSUE TITLE
[Bug]: Applio not running after installation (Windows)

### ISSUE THREAD

**Issue by OmgBro69** [IAHispano/Applio#888]
### Project Version

3.2.7

### Platform and OS Version

Windows 11 64bit 23H2

### Affected Devices

Pc

### What happened?

After installing Applio and running it an error shows up

### Steps to reproduce

1. Install Applio
2. Start Applio with "run-applio.bat"
3. Get the error
...

### Expected behavior

Open Applio Ui

### Attachments

Traceback (most recent call last):
  File "E:\tts\Applio-3.2.7\app.py", line 90, in <module>
    inference_tab()
  File "E:\tts\Applio-3.2.7\tabs\inference\inference.py", line 418, in inference_tab
    choices=get_speakers_id(model_file.value),
  File "E:\tts\Applio-3.2.7\tabs\inference\inference.py", line 325, in get_speakers_id
    model_data = torch.load(model, map_location="cpu")
  File "E:\tts\Applio-3.2.7\env\lib\site-packages\torch\serialization.py", line 1040, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "E:\tts\Applio-3.2.7\env\lib\site-packages\torch\serialization.py", line 1262, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
EOFError: Ran out of input

Press any key to continue . . .

**Comment by AznamirWoW** [comment]
Looks like a damaged model file

**Comment by OmgBro69** [comment]
After deleting my model file from the logs and installed via link in Applio everything works. : )
