### ISSUE TITLE
[Bug]: ImportError: cannot import name 'dependency_versions_check' from partially initialized module 'transformers'

### ISSUE THREAD

**Issue by Kelthic** [IAHispano/Applio#891]
### Project Version

3.2.7

### Platform and OS Version

Windows 11, 64 Bit

### Affected Devices

Windows

### What happened?

I've got problem after update:

`ImportError: cannot import name 'dependency_versions_check' from partially initialized module 'transformers' `

Any ideas how to fix that?

### Steps to reproduce

1. Update applio from 3.2.6 to 3.2.7
2. Done, you've got problem

### Expected behavior

Successeful update instead of any errors

### Attachments

```
Traceback (most recent call last):
  File "D:\Software\ApplioRVC\Applio-3.0.6\app.py", line 22, in <module>
    from tabs.inference.inference import inference_tab
  File "D:\Software\ApplioRVC\Applio-3.0.6\tabs\inference\inference.py", line 9, in <module>
    from core import (
  File "D:\Software\ApplioRVC\Applio-3.0.6\core.py", line 21, in <module>
    from rvc.lib.tools.model_download import model_download_pipeline
  File "D:\Software\ApplioRVC\Applio-3.0.6\rvc\lib\tools\model_download.py", line 15, in <module>
    from rvc.lib.utils import format_title
  File "D:\Software\ApplioRVC\Applio-3.0.6\rvc\lib\utils.py", line 14, in <module>
    from transformers import HubertModel
  File "D:\Software\ApplioRVC\Applio-3.0.6\env\lib\site-packages\transformers\__init__.py", line 26, in <module>
    from . import dependency_versions_check
ImportError: cannot import name 'dependency_versions_check' from partially initialized module 'transformers' (most likely due to a circular import) (D:\Software\ApplioRVC\Applio-3.0.6\env\lib\site-packages\transformers\__init__.py)
```

### Additional Information

Any help?

**Comment by blaisewf** [comment]
help was provided at discord. https://discord.com/channels/1096877223765606521/1287022888901152830/1312712177156751420
